"""Interaction QA against real application modules, with the offline bridge in offline_preview.
Run: python tests/ui/check_student_flow.py (requires Python Playwright + Chromium).
"""
import json
from pathlib import Path
import os, shutil
from playwright.sync_api import sync_playwright
from offline_preview import boot
OUT=Path(os.environ.get('OSED_QA_OUT',str(Path(__file__).resolve().parents[2]/'qa-output')))
OUT.mkdir(parents=True,exist_ok=True)
checks=[];errors=[]
def ok(label,value=True):
 assert value,label
 checks.append(label)
def trial(page,part='guided',review=False):
 return page.evaluate('''({part,review})=>{const s=JSON.parse(window.__store.data),t=review?s.teaching.review.trial:s.teaching.records[s.teaching.selected][part],id=review?s.teaching.review.id:s.teaching.selected,l=window.__testModules['tutor/catalog.js'].lessonById(id);return window.__testModules['tutor/models.js'].exercise(l.kind,t.seed)}''',{'part':part,'review':review})
def fill(page,x,wrong=False):
 a=x['answer']
 if x['answerType']=='choice':page.locator(f'input[name="answer"][value="{(a+1)%len(x["options"]) if wrong else a}"]').check()
 else:page.locator('#answer').fill(str(a+1 if wrong and isinstance(a,(int,float)) else '00 00 00 00' if wrong else a))
 page.get_by_role('button',name='Check answer',exact=False).click()
 page.locator('.feedback').wait_for()
def navigate_to_practice(page):
 page.get_by_role('button',name='Show me an example',exact=False).click()
 while page.locator('[data-action="watch-next"]').count():page.locator('[data-action="watch-next"]').click()
 page.get_by_role('button',name='Try with guidance',exact=False).click()
 page.locator('#answer-form').wait_for()

with sync_playwright() as p:
 b=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH') or shutil.which('chromium'),args=['--no-sandbox'])
 def new(width=1440,height=1000,dark=False,state=None,prefs=None,session=None):
  page=b.new_page(viewport={'width':width,'height':height},color_scheme='dark' if dark else 'light')
  page.on('pageerror',lambda err:errors.append(str(err)))
  boot(page,state,prefs,session);return page
 page=new()
 ok('First launch has one clear study CTA',page.locator('#main button.primary').count()==1)
 ok('First lesson is bytes, not a PDF or setup form','Bytes & addresses' in page.locator('#main').inner_text())
 page.screenshot(path=str(OUT/'OSED-Study-Home-Light.png'),full_page=True)
 page.get_by_role('button',name='Switch to dark mode').click()
 ok('Dark toggle switches all semantic tokens',page.locator('html').get_attribute('data-theme')=='dark')
 page.screenshot(path=str(OUT/'OSED-Study-Home-Dark.png'),full_page=True)
 page.get_by_role('button',name='Start lesson',exact=False).click()
 ok('Reader removes workspace navigation',page.locator('.sidebar').count()==0)
 ok('Reader names four stages',page.locator('.lesson-steps button').count()==4)
 ok('Reader has a single primary next action',page.locator('#main .primary').count()==1)
 ok('PDF references are collapsed',page.locator('.source-reference').get_attribute('open') is None)
 page.screenshot(path=str(OUT/'OSED-Study-Lesson-Dark.png'),full_page=True)
 page.get_by_role('button',name='Change reading size').click()
 page.get_by_role('button',name='Large',exact=True).click()
 ok('Reading-size dialog works',page.locator('html').get_attribute('data-reading-size')=='large')
 page.keyboard.press('Escape')
 ok('Escape closes the native dialog',page.locator('#modal').get_attribute('open') is None)
 page.get_by_role('button',name='Switch to light mode').click()
 page.screenshot(path=str(OUT/'OSED-Study-Lesson-Light.png'),full_page=True)
 navigate_to_practice(page)
 x=trial(page);fill(page,x)
 page.get_by_role('button',name='Try on my own',exact=False).click()
 x=trial(page,'solo');fill(page,x,wrong=True)
 ok('Wrong solo answer explains and offers a fresh case',page.locator('[data-action="fresh-solo"]').count()==1)
 page.locator('[data-action="fresh-solo"]').click();fill(page,trial(page,'solo'))
 page.get_by_role('button',name='Finish with a recap',exact=False).click()
 ok('Recap explains its disabled finish button',not page.locator('[data-action="complete"]').is_enabled())
 page.locator('#reflection').fill('An address is where the byte lives, not its value.')
 ok('Typing enables completion without leaving the field',page.locator('[data-action="complete"]').is_enabled())
 page.get_by_role('button',name='Complete lesson',exact=False).click()
 page.get_by_role('heading',name='Mission complete.').wait_for()
 ok('Full lesson finishes and saves',page.evaluate("JSON.parse(window.__store.data).teaching.records.bytes.completed"))
 ok('Windows practice is optional after completion',page.locator('.optional-lab').count()==1)
 page.get_by_role('button',name='Back to study',exact=True).first.click()
 ok('Home offers the next lesson after completion','Meet the CPU registers' in page.locator('.mission-copy h2').inner_text())
 page.locator('[data-view="notebook"]').click()
 ok('Notebook contains the recap','An address is where the byte lives' in page.locator('#main').inner_text())
 page.locator('[data-action="export"]').click()
 ok('Backup exports all saved learning data',page.evaluate('!!JSON.parse(window.__exported).teaching.records.bytes.completed'))
 page.locator('[data-view="settings"]').click()
 page.get_by_role('button',name='System',exact=True).click()
 page.emulate_media(color_scheme='dark');page.wait_for_timeout(100)
 ok('System mode follows live OS change',page.locator('html').get_attribute('data-theme')=='dark')
 page.get_by_role('button',name='Light',exact=True).click()
 page.emulate_media(color_scheme='dark');page.wait_for_timeout(80)
 ok('Explicit theme ignores system changes',page.locator('html').get_attribute('data-theme')=='light')
 page.get_by_role('button',name='Dark',exact=True).click()
 page.screenshot(path=str(OUT/'OSED-Study-Appearance.png'),full_page=True)
 state=page.evaluate('window.__store');prefs=page.evaluate('window.__prefs')
 second=new(state=state,prefs=prefs)
 ok('Theme survives a new renderer session',second.locator('html').get_attribute('data-theme')=='dark')
 ok('Reading size survives a new renderer session',second.locator('html').get_attribute('data-reading-size')=='large')
 ok('Progress survives a new renderer session',second.evaluate('JSON.parse(window.__store.data).teaching.records.bytes.completed'))
 second.get_by_role('button',name='Start lesson',exact=False).click()
 navigate_to_practice(second)
 snapshot=second.evaluate('window.__store');session=second.evaluate('window.__session')
 third=new(state=snapshot,prefs=prefs,session=session)
 ok('Interrupted study resumes in the same practice step',third.locator('#answer-form[data-part="guided"]').count()==1)
 # Review only a completed topic, by advancing that topic's due date in the test fixture.
 s=json.loads(state['data']);s['teaching']['records']['bytes']['due']='2020-01-01';rev=new(state={'revision':state['revision'],'data':json.dumps(s)})
 rev.locator('[data-view="review"]').click();rev.locator('[data-review-id="bytes"]').click();fill(rev,trial(rev,review=True));rev.locator('[data-action="end-review"]').click()
 ok('Review is completed without teaching an unseen topic','You’re all caught up.' in rev.locator('#main').inner_text())
 page.locator('[data-view="course"]').click()
 page.locator('#lesson-search').fill('pointer');page.wait_for_timeout(250)
 ok('Library search narrows by familiar lesson words',page.locator('.lesson-row').count()>0 and page.locator('.lesson-row').count()<10)
 page.locator('[data-course-tab="labs"]').click();page.locator('[data-native]').first.click()
 ok('Native walkthrough is reachable from the lab library',page.locator('.lab-setup').count()==1)
 page.locator('[data-action="leave-lab"]').click()
 ok('Windows walkthrough has an obvious exit','Windows labs' in page.locator('#main').inner_text())
 # All taught lessons remain discoverable in the library; orientation is in the source map.
 page.locator('[data-course-tab="lessons"]').click();page.locator('#lesson-search').fill('');page.wait_for_timeout(250)
 ok('All 56 study lessons remain present',page.locator('.lesson-row').count()==56)
 for w in [320,390,768,1024,1440]:
  responsive=new(width=w,height=900,dark=True)
  ok(f'Home fits {w}px',responsive.evaluate('document.documentElement.scrollWidth <= innerWidth'))
  responsive.get_by_role('button',name='Start lesson',exact=False).click()
  ok(f'Reader fits {w}px',responsive.evaluate('document.documentElement.scrollWidth <= innerWidth'))
  if w==390:responsive.screenshot(path=str(OUT/'OSED-Study-Mobile-Dark.png'),full_page=True)
  responsive.close()
 page.get_by_role('button',name='Help with studying').click()
 page.keyboard.press('Tab')
 ok('Help uses a modal dialog with keyboard focus',page.evaluate("document.querySelector('#modal').contains(document.activeElement)"))
 page.keyboard.press('Escape')
 page.emulate_media(reduced_motion='reduce')
 ok('Reduced motion disables UI transitions',page.evaluate("getComputedStyle(document.querySelector('#toast')).transitionDuration === '0s'"))
 ok('No browser JavaScript errors',not errors)
 b.close()
report={'checks':len(checks),'passed':checks,'javascript_errors':errors,'scope':'Actual UI modules in Chromium; mocked native persistence and device preferences. No claim of full manual Windows or iPhone QA.'}
(OUT/'OSED-Study-UI-QA.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
print(json.dumps(report,indent=2))
