// Original teaching summaries. Section/page references identify the uploaded EXP-301 v1.0 edition.
export const advancedRows=[
['seh',4,'An exception takes a different route','4.3 4.4.1',[93,97],'seh',
'An ordinary function return and exception dispatch are different control-flow events. In the x86 mechanism taught here, a thread has a chain of exception-registration records. Each record has a Next link and a Handler address. The system follows the links while looking for a handler that can deal with the exception.',
'Think of an emergency contact list. Next says where the next contact record is. Handler says which person to call. Mixing the two fields sends you to the wrong place.',
'Follow our two-record model by reading Next, not by treating Handler as another record. A changed handler can affect exception dispatch even when the original fault did not immediately replace EIP. The real course investigation observes both stages separately.',
'This is the x86 linked-record mechanism in the supplied edition, not an explanation of x64 exception handling. The model does not dispatch a real Windows exception.'],
['seh-checks',4,'A handler check is not a chain check','4.4.2',[99,102],'validation',
'SafeSEH and SEHOP ask different questions in this course. SafeSEH checks whether a handler is acceptable under a module’s handler metadata. SEHOP checks the integrity of the exception-registration chain. Identifying one protection does not answer the other question.',
'A guest list checks who may enter. Checking that an emergency-call list is intact is a different task. Passing the guest-list check does not repair a broken list.',
'Our exercise names the failed condition. Choose the check responsible for that condition rather than treating every exception failure as the same mitigation.',
'Operating-system defaults mentioned in this older book are not asserted as current defaults. Inspect the actual lab configuration before drawing conclusions.'],
['ppr',4,'Two POPs consume data; RET consumes a destination','4.5.2 4.5.4',[113,114],'ppr',
'At the beginning of a plain POP/POP/RET sequence, the first stack value goes into the first destination register. The second value goes into the second register. RET then takes the third value as the next instruction address. Each operation in this 32-bit model consumes one four-byte slot.',
'Three envelopes are queued. Open the first two as data. The third contains the next destination. Labelling all three envelopes “addresses to execute” loses the distinction.',
'Write an inventory of stack slots before stepping. Then track the cursor after every instruction. The course applies this reasoning to the arguments of an exception handler; our numbers are invented and the model performs no native execution.',
'We use ordinary general-purpose POP destinations and a plain RET. POP ESP and RET with an immediate require different accounting and are not silently treated as equivalent.'],
['relative-jump',4,'A short jump has a starting point and a distance','4.5.5',[124,126],'jump',
'A relative branch is easier to reason about after naming three things: the instruction address, its encoded length, and the signed displacement. For the original two-byte jump model here, destination = instruction address + 2 + displacement.',
'Walk to the end of the instruction first, then walk the signed distance. A negative distance goes backward. This is not a distance measured from an arbitrary stack label.',
'Our worked example shows the addition in separate steps. The fresh task changes the location and displacement, so remembering one familiar opcode pair is not enough.',
'The wording about the offset origin on source page 126 is ambiguous alongside its listing. This original model states its next-instruction-origin assumption explicitly; it is not a verbatim transcription of that sentence.'],
['static-dynamic',5,'Use a map, then check where you really are','5.1.2 5.1.3 5.1.4 5.2.1',[144,153],'branch',
'Static analysis shows possible code paths. Dynamic analysis shows the path taken with one particular input and program state. A branch drawn in the disassembler does not prove that your current input reaches it.',
'A street map shows possible turns. Your debugger is the observation of the turn you actually took. Use both when figuring out how to reach a particular place.',
'Name a condition, predict its result, and follow the matching edge. In the real workflow, names, comments and cross-references help you record the hypothesis; a breakpoint and observed values test it.',
'The book calls its IDA workflow “IDA Pro” generically, while page 136 specifies IDA Freeware. This lesson teaches the distinction between evidence from static and dynamic analysis, not a new tool requirement.'],
['ida-addresses',5,'An offset survives a changed module location','5.2.1',[151,153],'rebase',
'A static address and a live address can refer to the same instruction even when their numbers differ. Identify the module and calculate the instruction’s offset from its module base. Add that offset to the live module base to find the corresponding runtime location.',
'Apartment 0x240 is still the same position inside a building after the building is represented at a different location on a map.',
'Keep preferred/static base, runtime base, and relative offset in separate columns. The calculation is simple; confusing which number represents which thing is the common mistake.',
'This arithmetic assumes the same module build and relative layout. An offset from another binary version is not automatically valid.'],
['two-stages',6,'Small landing space, larger buffer elsewhere','6.5 6.5.1.1',[180,181],'tag',
'When the space initially reachable is too small, the course separates a small first stage from a larger second buffer. A distinctive tag helps identify the second buffer. First verify that the complete second buffer exists; only then reason about reaching it.',
'A small sign points to a larger workbench. The sign is not the workbench, and finding the sign is not the same as checking all the equipment behind it.',
'In our byte-array model, locate the full double tag and calculate the first byte after it. A lone half-tag is deliberately present as a distractor. No process-memory scan or payload runs.',
'The course’s exact request layout and tag are case-study details. Our synthetic tags and buffers are different. Secondary-buffer constraints must be tested independently.'],
['page-probes',6,'Do not assume every address is readable','6.5.2 6.6.2',[182,188],'page',
'An egghunter may encounter memory that is not mapped or cannot be read. A robust search must handle those cases instead of crashing while trying to find a buffer. The course examines a system-call-based probe and later an SEH-based approach.',
'Looking through rooms only works when you account for locked doors and missing rooms. A search that stops at the first locked door is not a reliable search.',
'Our small model uses pages of 0x1000 bytes, as in this course exercise. After an unreadable page, calculate the start of the next page rather than adding one to the same inaccessible address.',
'This is address arithmetic over invented pages. Actual probe results and portability depend on the target environment, which the following lesson treats separately.'],
['egghunter-portability',6,'When a familiar technique stops working, test its assumptions','6.6.3 6.7.2 6.7.3',[196,200],'portability',
'The book’s initial egghunter does not find a buffer that the debugger can see. That contradiction is useful evidence. Inspect the probe’s input registers and returned result, rather than assuming the buffer vanished or blindly increasing the search time.',
'A compass that points the wrong way is not fixed by walking farther. Check the instrument before continuing the journey.',
'The source investigates a changed system-call number and later differences affecting an SEH-based hunter. Our task asks which observation would discriminate between a search problem and a broken environmental assumption.',
'The source’s fixes are tied to its lab versions. This lesson does not claim a fixed syscall number or one SEH recipe is portable to all current systems.'],
['calling',7,'Who owns the arguments, result and cleanup?','7.1',[233,234],'calling',
'The x86 calling conventions used here put ordinary four-byte arguments on the stack in right-to-left order. The called function sees its return address before those arguments. In the course comparison, __stdcall performs argument cleanup in the callee; __cdecl leaves it to the caller.',
'Passing a parcel is not the entire agreement. You also need to know the order of the contents, where the receipt goes, and who clears the table afterward.',
'Count only the argument bytes when asked about argument cleanup. Keep the return-address slot separate. Also treat EAX, ECX and EDX as volatile across the calls discussed in the source unless you have a specific reason not to.',
'This simplified calculation uses four-byte arguments and the stated x86 conventions. It does not model every possible parameter type or a 64-bit ABI.'],
['loader-list',7,'Follow a pointer chain one dereference at a time','7.3.1',[236,238],'list',
'The source obtains module information through the TEB, PEB and loader data. Each step has a base, a field offset and often a pointer stored at that field. Adding an offset finds the field; reading the field obtains the next pointer. Those are separate operations.',
'A directory tells you where another directory lives. The address printed on a directory entry is not the content of the directory at that address.',
'Our model supplies two pointer fields. First calculate the field location, then read its value, then repeat. In the Windows exercise, verify the actual structures and embedded list offsets using symbols rather than guessing from a name.',
'Invented offsets keep this a pointer-reading exercise. Real TEB/PEB and embedded LIST_ENTRY offsets are given and investigated in the cited course section, not inferred from our diagram.'],
['exports',7,'Three export arrays, three different jobs','7.4.1 7.4.2',[245,247],'exports',
'Export-name lookup is a sequence. Find the desired name’s index in the names array. Read the corresponding entry in the name-ordinals array. Use that value as an index into the function-address array. The resulting RVA becomes a live address when added to the module base.',
'Think of a name catalogue, a ticket-number table and a location table. Your position in the catalogue is not automatically your location-table index.',
'Our three-entry example makes the indices deliberately different. Follow the arrows and calculate the final address. This is a synthetic subset of the course’s export-table reasoning, not a full PE loader.',
'Name indices, ordinal-table entries and function RVAs must not be conflated. Real target validation still matters; the exercise is not a complete implementation of every export case.'],
['hash-loop',7,'Understand one rotation before a whole hashing loop','7.4.3',[254,255],'rotate',
'The source’s name-hashing loop reads one character, checks for the terminator, rotates a 32-bit accumulator and adds the character. A rotation moves bits falling off one end back around to the other end; a shift does not do that.',
'Move seats around a circular table, rather than pushing chairs off a straight bench. A rotation wraps; a shift discards.',
'The first model asks for a one-bit rotation so the wrapping bit is visible. Once that is comfortable, trace the source’s rotate-and-add loop with a register table after each character.',
'The statement about collision freedom on source page 254 is not established by a proof there. Practising this algorithm does not establish that arbitrary strings always have unique 32-bit hashes.'],
['constraints',7,'Same arithmetic result, different encoded bytes','7.5.1',[263,265],'negate',
'An instruction sequence can work in a test harness but fail when sent through an input path that cannot carry some bytes. The course therefore checks the actual instruction bytes, not just the human-readable assembly. A different arithmetic construction may produce the value needed at runtime.',
'Two routes can arrive at the same destination while using different roads. The destination being valid does not mean every road is open.',
'Our 32-bit arithmetic model computes a value using negation modulo 2^32. This checks your understanding of the value calculation only. It does not claim that every resulting instruction encoding avoids a particular forbidden-byte set.',
'After any real instruction change, assemble it and inspect its bytes. Equivalent register results alone do not prove equivalent input compatibility or side effects.'],
['pic',7,'Use a runtime anchor instead of a remembered address','7.5.2',[265,266],'pic',
'Position-independent code must find what it needs without relying on the same absolute load address each time. The source uses a call’s saved return address as a runtime anchor. A known local offset can then locate another part of the same code.',
'“Twelve steps from where I am standing” can still work after the whole layout moves. “Go to yesterday’s street number” may not.',
'Our exercise gives an observed anchor and a relative offset, then changes the anchor in the solo problem. Calculate the target and explain which relationship stays the same.',
'The source also cares about the bytes of relative CALL/JMP instructions. This arithmetic drill does not by itself verify a full position-independent or NULL-free payload.'],
['api-contract',7,'An API prototype is a checklist, not decoration','7.6.1 7.6.2 7.6.3 7.6.4 7.6.5',[270,274],'api',
'The course builds custom shellcode by resolving required functions and supplying the arguments those functions expect. Handles, pointers, sizes and structures have different roles. A pointer to a structure is not interchangeable with the size of that structure.',
'A delivery form has a recipient, a parcel location and a parcel weight. Putting the weight in the address box does not become correct because both are numbers.',
'Before a call, annotate every argument by role and verify the memory behind pointer arguments. The mini-lab uses a benign copy-style contract so you can practise distinguishing an address from a byte count.',
'The later source subsections include network initialization and process-startup structures. They still need their own native assembly exercises; this contract lesson is not a replacement for those case-study tasks.'],
['protocol',8,'A rejected packet tells you where to investigate','8.2.3 8.2.4 8.3.1',[301,304],'protocol',
'Reverse engineering an input path begins by finding where input arrives and following the checks that accept or reject it. In the course, an early field is described as a checksum and its relationship to the remaining input length is investigated through static and dynamic analysis.',
'A receptionist rejecting your form is not evidence that the room you need is absent. Find the field that failed the first check, repair it, and observe the next checkpoint.',
'Our original record format is simpler: a four-byte length field followed by that many body bytes. Compute the body length from the total record size. Then explain why a rejected record has not yet tested the later copy operation.',
'This is an invented length-prefixed format. It does not reproduce the IBM protocol or silently redefine the book’s checksum terminology.'],
['input-path',8,'Trace the value that controls a copy','8.3.2 8.3.3 8.4.2',[342,348],'bounds',
'To investigate a memory copy, identify the source, destination and number of bytes. Then ask where that byte count came from and what bounds checks were applied. Knowing only that a copy function exists is not a vulnerability explanation.',
'“A worker moved boxes” is not the problem description. How many boxes, from where, into how much space, after which capacity check?',
'Our counted-copy model separates destination capacity from requested length. First calculate the amount beyond the boundary. In a real reversing session, verify whether the path is reachable and whether the count has already been constrained.',
'The model intentionally does not assume that a library function name alone makes a program vulnerable. It is a focused reasoning exercise, not a reproduction of the course application.'],
['dep',9,'Being readable does not make memory executable','9.1.1 9.1.2',[369,371],'permissions',
'DEP concerns whether instructions may execute from a page. It does not mean the bytes vanish, and it is not a general prevention of every out-of-bounds write. Distinguish reading data, writing data and fetching instructions.',
'A notebook can be readable and writable without being permission to give orders. Permission to inspect data is a different permission from executing it.',
'Our table supplies page permissions and a requested operation. Decide whether the operation is allowed under that simplified table. Observe that a successful write can coexist with a later execution failure.',
'The table is a teaching model of the distinction. Actual process policy and page protections must be inspected in the lab; historical defaults from the PDF are not treated as current universal defaults.'],
['rop',9,'A ROP chain is a changing stack cursor','9.2.2 9.4.4',[376,378],'rop',
'ROP combines existing instruction sequences while using stack data to supply values and subsequent destinations. To understand a sequence, record its input state, each changed register, each memory access and how far the stack pointer moves.',
'You are following small instruction cards using a queue of data. Some cards take extra entries from the queue. Forget one consumed entry and the next card is read from the wrong place.',
'Our example uses a gadget that pops two values and returns. Count both POPs and the return-address consumption. It deliberately includes an extra POP so you must account for more than the useful instruction.',
'These are invented instruction-state models, not gadgets taken from a real target. Passing them establishes local stack reasoning, not a working mitigation bypass.'],
['call-frame',9,'Build an argument layout before choosing instructions','9.4.3 9.4.5 9.4.6 9.4.7',[394,397],'callframe',
'The course places a function-call skeleton in memory and uses ROP to replace placeholders with values learned at runtime. Separate the function destination, its eventual return address and its arguments. Label them before trying to fill them.',
'Draw the labelled boxes on a form before filling the form. An unlabeled row of numbers is harder to repair than one with a name on every slot.',
'Our model begins exactly at entry to an x86 function: ESP points to the saved return address and four-byte arguments follow. Calculate the location of an argument. The model intentionally states this timing because a chain before entering the function has a different cursor.',
'Actual VirtualAlloc setup in the course spans more subsections than this small model. Each placeholder still needs runtime evidence in the real lab.'],
['aslr',10,'A leaked address is useful when you know what it points to','10.1.1 10.1.2 10.3.1',[430,432],'leak',
'An information leak may reveal an address inside a module. When the module build and the leaked location’s RVA are known, subtract that RVA to calculate the runtime base. Add another verified RVA to locate a different item in that same module.',
'Knowing where the third room is helps locate the building entrance only when you know how far the third room is from that entrance.',
'The exercise keeps leak, leak RVA, base and target RVA separate. Do the subtraction before the addition. A plausible-looking result is not enough: in the real lab verify it against the loaded module.',
'The source distinguishes system DLL reuse from application loading. Do not assume every DLL gets a different address on every process restart, or reuse an offset across different builds.'],
['copy-to-code',10,'Source buffer and executable destination are different','10.4.1',[466,471],'api',
'The course’s WriteProcessMemory approach copies bytes from a source buffer to a selected location in an already-executable code page. The argument roles matter: destination, source, byte count and the location used to receive a result are not interchangeable.',
'Copy a recipe from a workbench to a display board. The board location is the destination; the workbench location is the source; neither is the recipe length.',
'Our benign contract exercise checks roles only. Before a real call, verify capacity, permissions, the actual source bytes and whether overwriting the chosen destination damages code the process still needs.',
'The PDF explains this API’s behavior in its case study. This lesson does not generalize that behavior to every protected process or claim a complete native bypass.'],
['decode-before-copy',10,'Restore bytes before moving them to read-only code','10.4.2 10.4.3 10.4.4 10.4.5',[481,483],'decode',
'The course demonstrates a decoder failing because the copied code page is not writable. Its alternative restores substituted bytes while they are still in a suitable writable buffer, then performs the copy. The order matters as much as the byte arithmetic.',
'Correct the draft while it is on the writable workbench, then print it. Trying to erase and rewrite the final read-only display fails.',
'Our one-byte model calculates the additive adjustment modulo 256 that changes a transported byte back into the desired byte. Then explain why the correction belongs before the copy in this case.',
'The complete decoder also needs pointer alignment, gadget side effects and enough room for chain growth. Our arithmetic lab isolates one step; it does not verify the full generated chain.'],
['format-input',11,'Formatting instructions are different from ordinary text','11.1.1 11.1.2',[496,501],'format',
'A format string tells a formatting function how to interpret arguments. The course contrasts ordinary output with a bug where input can influence these formatting instructions. Distinguish the format argument from data supplied to a fixed format.',
'A printing instruction such as “show the next number” is not the same thing as the sentence you want printed. Treating an untrusted sentence as printing instructions changes its role.',
'The mini-lab compares a fixed format with user-controlled data against a user-controlled format. Identify which position controls interpretation; do not infer safety or exploitability from the presence of a percent sign alone.',
'This model does not run an unsafe formatting call. Real runtime behavior and available arguments determine what a specific format-string flaw permits.'],
['read-primitive',11,'A read primitive needs a path back to you','11.2.2 11.3.5 11.4.2 11.4.4',[548,557],'readpath',
'Reading memory internally is only part of a useful disclosure. The course also traces how data reaches an event log and how that output is retrieved. A read primitive needs a controlled or understood location and a way to observe the resulting bytes.',
'A camera capturing a picture does not help you until you can retrieve the picture. Follow both the capture path and the delivery path.',
'The exercise presents the missing link in a disclosure pipeline. Choose the observation that completes the pipeline. Keep a leaked stack address distinct from a module base address.',
'The source performs substantial case-specific reversing to establish this path. The lesson explains the dependency; it does not claim those detailed tasks are complete.'],
['write-primitive',12,'Writing a count is not printing a number','12.1.1 12.1.2',[568,570],'formatwrite',
'The %n family differs from ordinary display specifiers: it writes a character count through a supplied pointer. The course then works around target-specific limitations to create a useful write primitive. The value is tied to processed output, not the visible spelling of the target address.',
'A counter records how many tickets passed through the machine. Printing “100” on one ticket does not mean one hundred tickets passed through.',
'Our abstract counter starts with a known count and adds a chosen amount. Calculate the amount required to reach a larger target count. This small model does not execute printf or assume a particular runtime accepts %n.',
'The source notes that %n may be disabled by the runtime. Its later workarounds and byte-write behavior require separate target-specific validation.'],
['precision-writes',12,'Finish a multi-byte value before it is used','12.1.3 12.1.4 12.2.1',[583,585],'endian',
'The course combines smaller writes into a DWORD. Correct final bytes are not the only concern: the program must not consume a partially written value before all required writes are complete. Byte order and timing are separate requirements.',
'Replacing the digits of a destination one at a time is safe only if nobody acts on the half-edited address.',
'Our byte-order exercise checks the final four-byte representation. In your written explanation also state what could go wrong between the first and last write. The real lab must establish when the target value is consumed.',
'Completing this model is not proof that repeated native writes are atomic or reliable. The source explicitly discusses failures during multiple writes.'],
['pivot',12,'Changing EIP does not automatically place ESP correctly','12.3.1 12.3.2',[588,593],'pivot',
'ROP needs ESP to point to the data it will consume. A stack pivot changes that location. In the original model here, ESP is first moved to an allocated synthetic chain address; a plain RET then reads the first DWORD there into EIP and advances ESP by four.',
'You can open a recipe at the correct instruction while pointing at the wrong ingredient list. Moving the ingredient-list pointer is a separate job.',
'Track both registers after the pivot and after RET. The source’s real pivot has additional instructions, so each side effect must also be checked rather than stopping at the words “POP ESP”.',
'Our simplified pivot deliberately excludes those side effects. The native case is not verified merely by getting the two arithmetic answers correct.'],
['integration',13,'Build an evidence chain, not a collection of screenshots','13.1 13.2 13.3 13.4',[601,604],'workflow',
'The challenge chapter asks you to identify mitigations, reverse engineer vulnerabilities and develop an exploit. Each earlier skill contributes evidence to that process: input reachability, the corruption primitive, constraints, usable addresses, successful execution and reproduction.',
'An investigation needs connected observations explaining what caused what. A folder full of screenshots without those connections is not the explanation.',
'For an original practice target, first state the hypothesis, then the observation that would test it. Record unexpected results and rebuild from a clean state using your own notes. A guided worksheet and an independent target solve are different milestones.',
'The three official challenge targets are not bundled or reproduced. Full native challenge performance and reporting remain required practical work, distinct from these concept checks.']
];
