// Original teaching summaries. Section/page references identify the uploaded EXP-301 v1.0 edition.
export const advancedRows=[
['seh',4,'An exception takes a different route','4.3 4.4.1',[93,97],'seh',
'A function return and an exception send execution along different paths. In the x86 system taught here, each thread has a linked list of exception-registration records. Each record has two fields: Next points to the next record, and Handler points to code that may handle the exception. Windows follows the list to find a suitable handler.',
'Think of an emergency contact list. Next says where the next contact record is. Handler says which person to call. Mixing the two fields sends you to the wrong place.',
'Follow the Next field through our two-record model. The Handler field points to code, not to another record. Changing Handler can change where exception handling sends execution, even if the first fault did not replace EIP. Observe the fault and the later handler step separately in the real lab.',
'This is the x86 linked-record mechanism in the supplied edition, not an explanation of x64 exception handling. The model does not dispatch a real Windows exception.'],
['seh-checks',4,'A handler check is not a chain check','4.4.2',[99,102],'validation',
'SafeSEH and SEHOP check different things. SafeSEH checks whether a handler is allowed by the handler information stored for its module. SEHOP checks whether the linked list of exception-registration records is intact. Finding one protection tells you only about that protection.',
'A guest list checks who may enter. Checking that an emergency-call list is intact is a different task. Passing the guest-list check does not repair a broken list.',
'The exercise tells you what failed. Choose the protection that checks that condition. Different failures can come from different checks.',
'The book describes older operating systems. Their default settings may differ from yours. Inspect the settings in your lab before drawing a conclusion.'],
['ppr',4,'Two POPs consume data; RET consumes a destination','4.5.2 4.5.4',[113,114],'ppr',
'At the beginning of a plain POP/POP/RET sequence, the first stack value goes into the first destination register. The second value goes into the second register. RET then takes the third value as the next instruction address. Each operation in this 32-bit model consumes one four-byte slot.',
'Three envelopes are queued. Open the first two as data. The third contains the next destination. Labelling all three envelopes “addresses to execute” loses the distinction.',
'List the stack slots before stepping. After each instruction, record the new ESP value. The course uses this method for exception-handler arguments. Our example uses invented numbers and does not run native code.',
'This model pops into ordinary general-purpose registers and uses a plain RET. POP ESP and RET with an immediate value change the stack differently. Check those cases separately.'],
['relative-jump',4,'A short jump has a starting point and a distance','4.5.5',[124,126],'jump',
'To calculate a relative jump, find three values: the instruction address, the instruction length in bytes, and the signed displacement. Displacement means the distance to add after the instruction. In our two-byte model, destination = instruction address + 2 + displacement.',
'Walk to the end of the instruction first, then walk the signed distance. A negative distance goes backward. This is not a distance measured from an arbitrary stack label.',
'Our worked example shows the addition in separate steps. The fresh task changes the location and displacement, so remembering one familiar opcode pair is not enough.',
'Page 126 is unclear about where to measure the offset when read beside its code listing. This model states the rule directly: measure from the end of the jump instruction. The explanation here is original.'],
['static-dynamic',5,'Use a map, then check where you really are','5.1.2 5.1.3 5.1.4 5.2.1',[144,153],'branch',
'Static analysis shows possible code paths. Dynamic analysis shows the path taken with one particular input and program state. A branch drawn in the disassembler does not prove that your current input reaches it.',
'A street map shows possible turns. Your debugger is the observation of the turn you actually took. Use both when figuring out how to reach a particular place.',
'Name the condition, predict whether it is true or false, and follow that branch. Record your prediction with names, comments and cross-references in the disassembler. Then use a breakpoint and the real values to test it.',
'The book calls its IDA workflow “IDA Pro” generically, while page 136 specifies IDA Freeware. This lesson teaches the distinction between evidence from static and dynamic analysis, not a new tool requirement.'],
['ida-addresses',5,'An offset survives a changed module location','5.2.1',[151,153],'rebase',
'A static address and a live address can refer to the same instruction even when their numbers differ. Identify the module and calculate the instruction’s offset from its module base. Add that offset to the live module base to find the corresponding runtime location.',
'Apartment 0x240 is still the same position inside a building after the building is represented at a different location on a map.',
'Use three columns: the base shown in static analysis, the base in the running program, and the relative offset. Label each value before calculating so you do not use the wrong base.',
'This arithmetic assumes the same module build and relative layout. An offset from another binary version is not automatically valid.'],
['two-stages',6,'Small landing space, larger buffer elsewhere','6.5 6.5.1.1',[180,181],'tag',
'Sometimes execution first reaches a space that is too small for all the code. The course uses a small first stage there and a larger second buffer elsewhere. A unique-looking byte pattern, called a tag, helps find the second buffer. First check that the whole second buffer is present. Then work out how to reach it.',
'A small sign points to a larger workbench. The sign is not the workbench, and finding the sign is not the same as checking all the equipment behind it.',
'In our byte array, find the complete double tag and calculate the address of the first byte after it. The array also contains a half-tag to test whether you check both parts. This model runs no process-memory scan or payload.',
'The course uses its own request layout and tag. Our tags and buffers are invented. Test the limits on the second buffer separately in the real lab.'],
['page-probes',6,'Do not assume every address is readable','6.5.2 6.6.2',[182,188],'page',
'An egghunter is a small routine that searches memory for a tagged buffer. It may reach memory that is not mapped or cannot be read. It must handle these cases so the search can continue. The course first tests access with a system call, then uses an approach based on SEH.',
'Looking through rooms only works when you account for locked doors and missing rooms. A search that stops at the first locked door is not a reliable search.',
'Our small model uses pages of 0x1000 bytes, as in this course exercise. After an unreadable page, calculate the start of the next page rather than adding one to the same inaccessible address.',
'These pages are invented for address practice. Whether a real probe works depends on the target system. The next lesson examines those system differences.'],
['egghunter-portability',6,'When a familiar technique stops working, test its assumptions','6.6.3 6.7.2 6.7.3',[196,200],'portability',
'The book’s initial egghunter does not find a buffer that the debugger can see. That contradiction is useful evidence. Inspect the probe’s input registers and returned result, rather than assuming the buffer vanished or blindly increasing the search time.',
'A compass that points the wrong way is not fixed by walking farther. Check the instrument before continuing the journey.',
'The source investigates a changed system-call number, then system differences that affect an SEH-based hunter. Choose the observation that helps you tell two causes apart: a problem in the search, or an assumption that is wrong for this system.',
'The source fixes apply to its lab versions. A syscall number or SEH method that works there may fail on another system. Test it in the actual target environment.'],
['calling',7,'Who owns the arguments, result and cleanup?','7.1',[233,234],'calling',
'A calling convention defines how a function receives arguments and returns. The x86 conventions used here put ordinary four-byte arguments on the stack from right to left. At function entry, the return address comes before the arguments. With __stdcall, the called function, or callee, removes the arguments. With __cdecl, the caller removes them.',
'Passing a parcel is not the entire agreement. You also need to know the order of the contents, where the receipt goes, and who clears the table afterward.',
'For argument cleanup, count only the argument bytes. Keep the return-address slot separate. EAX, ECX and EDX are volatile for the calls discussed here: the called function may change them. Do not expect their old values to survive unless you have checked that specific call.',
'This simplified calculation uses four-byte arguments and the stated x86 conventions. It does not model every possible parameter type or a 64-bit ABI.'],
['loader-list',7,'Follow a pointer chain one dereference at a time','7.3.1',[236,238],'list',
'The source follows Windows structures to find module information: the Thread Environment Block (TEB), the Process Environment Block (PEB), and loader data. To follow a pointer field, add its offset to the current base address. Then read the pointer stored there. Adding the offset and reading memory are separate steps.',
'A directory tells you where another directory lives. The address printed on a directory entry is not the content of the directory at that address.',
'Our model supplies two pointer fields. First calculate the field location, then read its value, then repeat. In the Windows exercise, verify the actual structures and embedded list offsets using symbols rather than guessing from a name.',
'The offsets here are invented for pointer practice. Use the cited course section to study real TEB, PEB and embedded LIST_ENTRY offsets. Do not take real offsets from this diagram.'],
['exports',7,'Three export arrays, three different jobs','7.4.1 7.4.2',[245,247],'exports',
'To find an exported function by name, follow three arrays. First, find the name in the names array and note its index. At that same index in the name-ordinals array, read a new index. Use that new index in the function-address array to get the function RVA. Add the module base to that RVA to get the address in memory.',
'Think of a name catalogue, a ticket-number table and a location table. Your position in the catalogue is not automatically your location-table index.',
'The indices in our three-entry example are different on purpose. Follow each arrow and calculate the final address. This invented example teaches one part of export lookup. It is not a full PE loader.',
'Keep the name index, ordinal-table entry and function RVA separate. Check the result in the real target. This exercise does not cover every kind of export.'],
['hash-loop',7,'Understand one rotation before a whole hashing loop','7.4.3',[254,255],'rotate',
'The name-hashing loop reads a character and stops if it is the string terminator. Otherwise, it rotates an accumulator, the register holding the current 32-bit result, and adds the character value. A rotation wraps bits from one end back to the other. A shift does not wrap them.',
'Move seats around a circular table, rather than pushing chairs off a straight bench. A rotation wraps; a shift discards.',
'The first model asks for a one-bit rotation so the wrapping bit is visible. Once that is comfortable, trace the source’s rotate-and-add loop with a register table after each character.',
'A collision means two different inputs produce the same hash. Page 254 gives no proof for its claim about avoiding collisions. Learning this algorithm does not show that every string has a unique 32-bit hash.'],
['constraints',7,'Same arithmetic result, different encoded bytes','7.5.1',[263,265],'negate',
'Instructions may work in a small test program but fail after passing through an input path that changes or blocks some bytes. Check the assembled instruction bytes as well as the assembly text. You may need different instructions to build the same value while using bytes the input path accepts.',
'Two routes can arrive at the same destination while using different roads. The destination being valid does not mean every road is open.',
'Our model uses 32-bit negation modulo 2^32: subtract the number from zero and keep the low 32 bits. This tests the value calculation only. It does not check whether the assembled instructions avoid the bytes forbidden by an input path.',
'After changing real instructions, assemble them and inspect their bytes. Two sequences can produce the same register value but use different bytes or change other parts of the program state.'],
['pic',7,'Use a runtime anchor instead of a remembered address','7.5.2',[265,266],'pic',
'Position-independent code can work when loaded at different addresses. It finds nearby code or data from a known point at runtime. The source uses the return address saved by a call as that point, or anchor. Adding a known local offset then locates another part of the same code.',
'“Twelve steps from where I am standing” can still work after the whole layout moves. “Go to yesterday’s street number” may not.',
'Our exercise gives an observed anchor and a relative offset, then changes the anchor in the solo problem. Calculate the target and explain which relationship stays the same.',
'The source also cares about the bytes of relative CALL/JMP instructions. This arithmetic drill does not by itself verify a full position-independent or NULL-free payload.'],
['api-contract',7,'An API prototype is a checklist, not decoration','7.6.1 7.6.2 7.6.3 7.6.4 7.6.5',[270,274],'api',
'To call an API, first find the function address and check its prototype: the definition of its arguments and result. Each argument has a role, such as a handle, pointer or size. A pointer gives the address of a structure; a size says how many bytes it uses. Supply the value each argument expects.',
'A delivery form has a recipient, a parcel location and a parcel weight. Putting the weight in the address box does not become correct because both are numbers.',
'Before a call, label each argument with its role. For a pointer argument, check the memory it points to. Our harmless copy example asks you to tell an address from a byte count and place each in the correct argument slot.',
'The later source subsections include network initialization and process-startup structures. They still need their own native assembly exercises; this contract lesson is not a replacement for those case-study tasks.'],
['protocol',8,'A rejected packet tells you where to investigate','8.2.3 8.2.4 8.3.1',[301,304],'protocol',
'To reverse engineer an input path, find where input enters the program. Then follow the checks that accept or reject it. The course calls one early field a checksum. It uses static analysis and debugger observations to investigate how that field relates to the length of the remaining input.',
'A receptionist rejecting your form is not evidence that the room you need is absent. Find the field that failed the first check, repair it, and observe the next checkpoint.',
'Our original record format is simpler: a four-byte length field followed by that many body bytes. Compute the body length from the total record size. Then explain why a rejected record has not yet tested the later copy operation.',
'This is an invented length-prefixed format. It does not reproduce the IBM protocol or silently redefine the book’s checksum terminology.'],
['input-path',8,'Trace the value that controls a copy','8.3.2 8.3.3 8.4.2',[342,348],'bounds',
'To investigate a memory copy, identify the source, destination and number of bytes. Then ask where that byte count came from and what bounds checks were applied. Knowing only that a copy function exists is not a vulnerability explanation.',
'“A worker moved boxes” is not the problem description. How many boxes, from where, into how much space, after which capacity check?',
'Our model gives two values: the space available at the destination and the requested copy length. Calculate how many bytes would cross the boundary. In a real program, check that your input reaches the copy and whether an earlier check has already limited the count.',
'The model intentionally does not assume that a library function name alone makes a program vulnerable. It is a focused reasoning exercise, not a reproduction of the course application.'],
['dep',9,'Being readable does not make memory executable','9.1.1 9.1.2',[369,371],'permissions',
'Data Execution Prevention (DEP) limits which memory pages can run instructions. A page can still hold readable data when execution is blocked. DEP also does not stop every write beyond a buffer. Check three permissions separately: reading, writing and executing.',
'A notebook can be readable and writable without being permission to give orders. Permission to inspect data is a different permission from executing it.',
'Our table gives page permissions and an operation to check. Decide whether the table allows that operation. Notice that writing bytes may succeed even when trying to execute those bytes later fails.',
'This table is a teaching model. Inspect the process settings and page protections in the real lab. The older defaults in the PDF may differ from your system.'],
['rop',9,'A ROP chain is a changing stack cursor','9.2.2 9.4.4',[376,378],'rop',
'Return-Oriented Programming (ROP) links short instruction sequences already in a program. These sequences are called gadgets. Stack entries provide values and the addresses of later gadgets. For each gadget, record the starting state, register changes, memory accesses and movement of ESP.',
'You are following small instruction cards using a queue of data. Some cards take extra entries from the queue. Forget one consumed entry and the next card is read from the wrong place.',
'Our gadget pops two values and then returns. Count one stack slot for each POP and one for RET. Include the extra POP even if its value is not useful. Every instruction affects where the chain reads next.',
'These are invented instruction-state models, not gadgets taken from a real target. Passing them establishes local stack reasoning, not a working mitigation bypass.'],
['call-frame',9,'Build an argument layout before choosing instructions','9.4.3 9.4.5 9.4.6 9.4.7',[394,397],'callframe',
'The course first lays out the slots needed for a function call in memory. ROP then fills these slots with values found while the program runs. Label the function address, the address to return to afterward, and each argument before filling them.',
'Draw the labelled boxes on a form before filling the form. An unlabeled row of numbers is harder to repair than one with a name on every slot.',
'This model starts at the moment an x86 function begins. ESP points to the saved return address; the four-byte arguments come after it. Calculate an argument address from this layout. Before the function starts, ESP may point to a different slot, so always state the moment you are tracing.',
'Actual VirtualAlloc setup in the course spans more subsections than this small model. Each placeholder still needs runtime evidence in the real lab.'],
['aslr',10,'A leaked address is useful when you know what it points to','10.1.1 10.1.2 10.3.1',[430,432],'leak',
'An information leak may reveal an address inside a module. If you know the module build and that location’s relative virtual address (RVA), subtract the RVA from the leaked address. The result is the module base in the running process. Add another verified RVA to find another item in that same module.',
'Knowing where the third room is helps locate the building entrance only when you know how far the third room is from that entrance.',
'Label four values: the leaked address, its RVA, the module base and the target RVA. Subtract first, then add. In the real lab, compare your result with the loaded module; a number that looks reasonable can still be wrong.',
'The source distinguishes system DLL reuse from application loading. Do not assume every DLL gets a different address on every process restart, or reuse an offset across different builds.'],
['copy-to-code',10,'Source buffer and executable destination are different','10.4.1',[466,471],'api',
'In the course example, WriteProcessMemory copies bytes from a source buffer into a chosen location on a page that already allows execution. Label each argument carefully: where to copy to, where to copy from, how many bytes to copy, and where to store the result. Each has a different role.',
'Copy a recipe from a workbench to a display board. The board location is the destination; the workbench location is the source; neither is the recipe length.',
'Our benign contract exercise checks roles only. Before a real call, verify capacity, permissions, the actual source bytes and whether overwriting the chosen destination damages code the process still needs.',
'The PDF explains this API’s behavior in its case study. This lesson does not generalize that behavior to every protected process or claim a complete native bypass.'],
['decode-before-copy',10,'Restore bytes before moving them to read-only code','10.4.2 10.4.3 10.4.4 10.4.5',[481,483],'decode',
'In the course, a decoder fails when it tries to change bytes on a code page that is not writable. The alternative fixes the changed bytes while they are still in a writable buffer, then copies them to the code page. Check both the byte calculation and the order of these steps.',
'Correct the draft while it is on the writable workbench, then print it. Trying to erase and rewrite the final read-only display fails.',
'Our model asks how much to add to one received byte to restore the desired byte. Use modulo 256: if the sum reaches 256, wrap back to zero. Then explain why this example must fix the byte before copying it.',
'The complete decoder also needs pointer alignment, gadget side effects and enough room for chain growth. Our arithmetic lab isolates one step; it does not verify the full generated chain.'],
['format-input',11,'Formatting instructions are different from ordinary text','11.1.1 11.1.2',[496,501],'format',
'A format string tells a formatting function how to use its arguments. For example, it may ask the function to print a number or string. The course studies a bug where input can control these instructions. First identify the format argument, then identify the data arguments.',
'A printing instruction such as “show the next number” is not the same thing as the sentence you want printed. Treating an untrusted sentence as printing instructions changes its role.',
'Compare two cases: input passed as data to a fixed format, and input used as the format itself. Find which argument controls how the function interprets the others. A percent sign alone does not prove that the code is safe or exploitable.',
'This model does not run an unsafe formatting call. Real runtime behavior and available arguments determine what a specific format-string flaw permits.'],
['read-primitive',11,'A read primitive needs a path back to you','11.2.2 11.3.5 11.4.2 11.4.4',[548,557],'readpath',
'A read primitive is a way to make a program read memory at a chosen or understood location. To use it for disclosure, you also need to see the bytes it reads. The course traces both parts: how data reaches an event log and how that log is retrieved.',
'A camera capturing a picture does not help you until you can retrieve the picture. Follow both the capture path and the delivery path.',
'The exercise leaves out one step between reading memory and seeing the output. Choose the observation that confirms the missing step. Also keep a leaked stack address separate from a module base address.',
'The source requires detailed reverse engineering of its target to prove this path. This lesson explains why both parts are needed. It does not complete those practical tasks.'],
['write-primitive',12,'Writing a count is not printing a number','12.1.1 12.1.2',[568,570],'formatwrite',
'The %n family stores a count at the address supplied by a pointer: how many characters this formatting call has written so far. It does not print that count. The course works around limits in its target to turn this behavior into a write primitive, a way to change memory. The stored value comes from the output count, not the digits in the address.',
'A counter records how many tickets passed through the machine. Printing “100” on one ticket does not mean one hundred tickets passed through.',
'Our abstract counter starts with a known count and adds a chosen amount. Calculate the amount required to reach a larger target count. This small model does not execute printf or assume a particular runtime accepts %n.',
'The source notes that %n may be disabled by the runtime. Its later workarounds and byte-write behavior require separate target-specific validation.'],
['precision-writes',12,'Finish a multi-byte value before it is used','12.1.3 12.1.4 12.2.1',[583,585],'endian',
'The course builds a DWORD with several smaller writes. Check the final bytes, but also check when the program uses that value. If it reads the value before all writes finish, it may use a mix of old and new bytes. Both byte order and timing must be correct.',
'Replacing the digits of a destination one at a time is safe only if nobody acts on the half-edited address.',
'Our exercise checks the final order of four bytes. Also explain what could go wrong between the first and last write. In the real lab, find out exactly when the program reads and uses the target value.',
'Passing this model does not show that real writes are reliable or atomic. Atomic means other code cannot observe a partially completed update. The source discusses failures between multiple writes.'],
['pivot',12,'Changing EIP does not automatically place ESP correctly','12.3.1 12.3.2',[588,593],'pivot',
'A ROP chain needs ESP to point to its next stack entry. A stack pivot moves ESP to another location. In our invented model, ESP moves to an allocated buffer holding a chain. A plain RET then reads the first DWORD into EIP and adds four to ESP.',
'You can open a recipe at the correct instruction while pointing at the wrong ingredient list. Moving the ingredient-list pointer is a separate job.',
'Track both registers after the pivot and after RET. The source’s real pivot has additional instructions, so each side effect must also be checked rather than stopping at the words “POP ESP”.',
'Our simple model leaves out those extra effects. Correct EIP and ESP calculations here do not prove that the full pivot works in a native program.'],
['integration',13,'Build an evidence chain, not a collection of screenshots','13.1 13.2 13.3 13.4',[601,604],'workflow',
'The challenge chapter asks you to identify protections, reverse engineer vulnerabilities and develop an exploit. Use earlier skills to answer each question: Can your input reach the bug? What memory can it change? What limits apply? Which addresses can you use? Does execution succeed? Can you repeat the result from a clean start?',
'An investigation needs connected observations explaining what caused what. A folder full of screenshots without those connections is not the explanation.',
'For an original practice target, write your prediction and the observation that would test it. Record unexpected results. Then rebuild from a clean state using your own notes. Completing a guided worksheet and solving a target independently are separate milestones.',
'The three official challenge targets are not bundled or reproduced. Full native challenge performance and reporting remain required practical work, distinct from these concept checks.']
];
