import {lessons,lessonById,chapters,modes} from './catalog.js';
import {sourceIndex} from './coverage.js';
import {exercise,check,answerText} from './models.js';
import {normalize,ensureRecord,submit,complete,canComplete,retry,dueLessons,startReview,answerReview} from './state.js';
import {native,invoke,load,persist,exportData} from './storage.js';
import {guideFor} from './windows.js';
import {day,pauseOnLoad} from '../engine.js';
const $=s=>document.querySelector(s);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?.()||Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
let S,view='learn',menu=false,filter='',chapterFilter=0,sourceFilter=0,vmStep=0,info={},busy=false,toastTimer,searchTimer;
const lesson=()=>lessonById(S.teaching.selected);
const record=()=>ensureRecord(S,lesson().id,uid());
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),6500);}
function error(err){console.error(err);toast(err?.message||String(err));const n=$('#saved');if(n)n.textContent='Check save / export backup';}
async function save(){await persist(S);const n=$('#saved');if(n)n.textContent='Saved on this device';}
function table(t){return `<div class="table-wrap"><table><thead><tr>${t.headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
const tag=t=>`<span class="tag">${esc(t)}</span>`;
const button=(a,t,cls='')=>`<button class="${cls}" data-action="${a}">${t}</button>`;
function source(l){return `<details class="source"><summary>Only the related source · §${esc(l.sections.join(', §'))} · ${l.pages[0]===l.pages[1]?'p. '+l.pages[0]:'pp. '+l.pages.join('–')}</summary><p>${esc(l.scope)}</p><p class="small">Original explanations and invented examples above; topic references are to your uploaded EXP-301 v1.0 / ©2021 edition. These page references are optional reinforcement, not a chapter-reading assignment.</p>${native?button('pdf',`Open my linked PDF (then navigate to p. ${l.pages[0]})`):'<p class="small">Use these exact section references in your own PDF. The course file is not included or uploaded.</p>'}</details>`;}
function title(eyebrow,head,desc=''){return `<header class="page-title"><span class="eyebrow">${esc(eyebrow)}</span><h1>${esc(head)}</h1>${desc?`<p>${esc(desc)}</p>`:''}</header>`;}
function top(){const r=record(),l=lesson(),count=Object.values(S.teaching.records).filter(r=>r.completed).length;return `<header class="top"><button class="brand" data-action="home"><span class="brand-mark">F</span><span>OSED <b>Forge</b><small>GUIDED LEARNING · 0.2</small></span></button><nav aria-label="Main navigation">${['learn','review','coverage','journal','settings'].map(v=>`<button class="nav ${view===v?'active':''}" data-view="${v}">${({learn:'Learn',review:'Review',coverage:'Course coverage',journal:'Journal',settings:'Settings'})[v]}${v==='review'&&dueLessons(S).length?` <span class="count">${dueLessons(S).length}</span>`:''}</button>`).join('')}</nav><span id="saved" class="small">Saved on this device</span></header><div class="subbar"><button data-action="menu">☰ Lessons <span class="small">${count}/${lessons.length} concept checks</span></button><span class="small">${esc(S.settings.name)} · ${esc(S.settings.weeklyHours)} h/week · local/offline</span></div>`;}
function menuHTML(){return `<aside class="lesson-menu ${menu?'open':''}" aria-label="Lesson library"><div class="menu-head"><h2>Your learning path</h2>${button('menu','Close ×')}</div><p class="small">Suggested order. Browse ahead freely; nothing is marked learned just by opening it.</p><label class="sr-only" for="lesson-search">Search lessons</label><input id="lesson-search" type="search" placeholder="Find a concept…" value="${esc(filter)}"><label class="sr-only" for="chapter-filter">Filter by chapter</label><select id="chapter-filter"><option value="0">All chapters</option>${chapters.slice(1).map((t,i)=>`<option value="${i+1}" ${chapterFilter===i+1?'selected':''}>${i+1} · ${esc(t)}</option>`).join('')}</select><div class="lesson-list">${lessons.filter(l=>(!chapterFilter||l.chapter===chapterFilter)&&`${l.title} ${l.sections.join(' ')}`.toLowerCase().includes(filter.toLowerCase())).map(l=>`<button class="lesson-link ${S.teaching.selected===l.id?'selected':''}" data-lesson="${l.id}"><span class="lesson-num">${S.teaching.records[l.id]?.completed?'✓':String(l.order+1).padStart(2,'0')}</span><span>${esc(l.title)}<small>Chapter ${l.chapter} · ${l.minutes} min estimate</small></span></button>`).join('')}</div></aside>`;}
function learn(){const l=lesson(),r=record();return `<div class="learning-layout"><section class="learning-main">${title(`CONCEPT ${l.order+1} · ${chapters[l.chapter]}`,l.title)}<div class="lesson-meta">${tag(l.minutes+' estimate')}${tag(r.completed?'Concept check passed':'One idea, one step at a time')}${tag('No PDF reading needed to start')}</div><div class="step-tabs" role="group" aria-label="Lesson stages">${modes.map((m,i)=>`<button data-step="${i}" class="${r.step===i?'current':''}" aria-current="${r.step===i?'step':'false'}"><span>${i+1}</span>${m}</button>`).join('')}</div>${stage(l,r)}${source(l)}</section><aside class="context"><div class="context-card"><span class="eyebrow">TODAY’S JOB</span><h3>Understand this one idea.</h3><p>Predict a value. See why it changes. Try a fresh case. Explain it in your own words.</p><div class="quiet-rule"></div><p class="small">The mini-labs run a simplified teaching model—not a Windows process. Real debugger practice is a separate stage.</p></div><details class="context-card"><summary>Words you can look up</summary><dl><dt>Address</dt><dd>A location in memory.</dd><dt>Value</dt><dd>The contents stored at a location.</dd><dt>Pointer</dt><dd>A value interpreted as an address.</dd><dt>Register</dt><dd>A small CPU working-storage location.</dd><dt>DWORD</dt><dd>A four-byte value in these exercises.</dd><dt>Offset</dt><dd>A distance from a named starting point.</dd><dt>Dereference</dt><dd>Read through a pointer to its destination.</dd></dl></details>${l.previous?`<div class="context-card"><p class="small">Need the preceding building block?</p><button data-lesson="${l.previous}">${esc(lessonById(l.previous).title)} ←</button></div>`:''}</aside></div>`;}
function modelState(x,i){const s=x.states?.[i];return s?`<section class="model-state" aria-label="Illustrative register and memory state"><span class="eyebrow">SEE THE STATE · INVENTED MODEL VALUES</span><div class="register-row">${Object.entries(s.registers).map(([k,v])=>`<div><small>${esc(k)}</small><code>${esc(v)}</code></div>`).join('')}</div>${table({headers:['Memory address','Stored value','Meaning'],rows:s.memory})}<p class="small">A visual teaching state, not output captured from a debugger.</p></section>`:'';}
function stage(l,r){
 if(r.step===0)return `<article class="lesson-card"><span class="eyebrow">LEARN · THE IDEA</span><p class="teaching">${esc(l.explain)}</p><details class="simpler"><summary>Explain it more simply</summary><p>${esc(l.simple)}</p></details><div class="why"><h3>What to pay attention to</h3><p>${esc(l.practice)}</p></div><div class="bottom-actions">${button('watch','Show me an example →','primary')}</div></article>`;
 if(r.step===1){const x=exercise(l.kind,l.id+':worked'),i=Math.min(r.watch,x.steps.length-1);return `<article class="lesson-card"><span class="eyebrow">WATCH · WORKED EXAMPLE</span><h2>${esc(x.prompt)}</h2>${table(x.display)}<div class="worked-step"><span class="step-number">${i+1}/${x.steps.length}</span><div><span class="eyebrow">FOLLOW THE CHANGE</span><p>${esc(x.steps[i])}</p></div></div>${modelState(x,i)}<div class="step-dots">${x.steps.map((_,j)=>`<span class="${j<=i?'on':''}"></span>`).join('')}</div><div class="bottom-actions">${button('watch-back','← Previous',i===0?'invisible':'')}${i<x.steps.length-1?button('watch-next','Next change →','primary'):button('guided','Now guide me through one →','primary')}</div><p class="small">These are invented values with the model’s assumptions stated. Nothing is executing in your Windows VM.</p></article>`;}
 if(r.step===2||r.step===3){const part=r.step===2?'guided':'solo';return `<article class="lesson-card">${practice(l,r[part],part)}<div class="bottom-actions">${part==='guided'&&r.guided.correct?button('solo','Try a different one on my own →','primary'):''}${part==='solo'&&r.solo.correct&&!r.solo.revealed&&r.solo.hints===0&&r.solo.tries===1?button('remember','Explain what I learned →','primary'):''}${part==='solo'&&r.solo.tries>0&&!canComplete({...r,reflection:'temporary explanation'})?'<p class="small">After studying feedback, use “Fresh case” for a first-try check without a revealed answer.</p>':''}</div></article>`;}
 if(r.step===4)return `<article class="lesson-card"><span class="eyebrow">REMEMBER · PUT IT IN YOUR WORDS</span><h2>What mattered—and why?</h2><p>Explain the key distinction and one mistake you now know to avoid. This is your reflection, not an AI-graded essay.</p><label for="reflection">Your explanation</label><textarea id="reflection" maxlength="5000" rows="5" placeholder="The location is different from the value because…">${esc(r.reflection)}</textarea><p class="small">Saved when you leave the field. No cloud or AI service reads this text.</p><div class="bottom-actions">${r.completed?`<span class="passed">✓ Concept check recorded · next review ${esc(r.due)}</span>`:button('complete','Save concept check','primary')}${button('windows','Connect it to Windows practice →')}</div>${r.completed?button('next-lesson','Continue to the next idea →','primary'):''}<p class="small">A concept check requires guided success, a fresh first-try solo answer without hints/reveal, and your reflection. It is not an exploit certification.</p></article>`;
 return windows(l,r);
}
function practice(l,t,part,reviewMode=false){const x=exercise(l.kind,t.seed),done=reviewMode?S.teaching.review.recorded:t.correct||t.revealed;return `<span class="eyebrow">${reviewMode?'RETRIEVAL CHECK':part==='guided'?'GUIDED · YOUR TURN WITH SUPPORT':'SOLO · CHANGED CASE'}</span><h2>${esc(x.prompt)}</h2>${table(x.display)}<form id="answer-form" data-part="${part}" data-review="${reviewMode}">${x.answerType==='choice'?`<fieldset><legend>Choose your answer</legend>${x.options.map((o,i)=>`<label class="option"><input type="radio" name="answer" value="${i}" ${t.answer===String(i)?'checked':''} ${done?'disabled':''} required><span>${esc(o)}</span></label>`).join('')}</fieldset>`:`<label for="answer">${x.answerType==='bytes'?'Four byte pairs, for example 12 34 56 78':'Enter decimal or hexadecimal beginning with 0x'}</label><input id="answer" name="answer" autocomplete="off" spellcheck="false" maxlength="160" value="${esc(t.answer)}" ${done?'disabled':''} required>`}<div class="bottom-actions">${!done?'<button type="submit" class="primary">Check my reasoning</button>':''}${!reviewMode&&!done?button('hint','Give me a hint'):''}${!reviewMode?button('fresh-'+part,'Fresh case'):''}</div></form>${t.hints?`<div class="hint"><b>A nudge</b>${x.hints.slice(0,t.hints).map(h=>`<p>${esc(h)}</p>`).join('')}</div>`:''}${t.tries||t.revealed?`<div class="feedback ${t.correct?'good':'needs-work'}"><h3>${t.correct?(part==='solo'&&(t.hints||t.revealed||t.tries>1)?'Correct after support / retry':'That follows the model.'):(t.revealed?'Worked solution':'Not yet. Check the distinction.')}</h3><p>${esc(x.explanation)}</p>${t.correct||t.revealed||reviewMode?`<p><b>Answer: ${esc(answerText(x))}</b></p>${x.steps.map(s=>`<p>${esc(s)}</p>`).join('')}`:`<p>${esc(x.hints[0])}</p>${button('reveal','Show the reasoning (assisted)')}`}</div>`:''}<p class="small">${reviewMode?'Only a topic you already completed can appear here.':part==='guided'?'Use hints freely. This step is for learning, not scoring.':'A hint, revealed answer or failed try is recorded as supported practice. A fresh first-try case checks transfer.'}</p>`;}
function windows(l,r){const g=guideFor(l);if(!g)return `<article class="lesson-card"><span class="eyebrow">NATIVE PRACTICE · NOT YET AUTHORED</span><h2>This concept is taught; its full Windows exploit lab is not bundled.</h2><p>The model above is useful for understanding the mechanism, but it is not an executable version of the course case study. The coverage page keeps that gap visible.</p><p>Related source: §${esc(l.sections.join(', §'))}. Use your licensed course environment for the corresponding native exercise; these exact references are the bridge, not a claim that the exercise has been replaced.</p><label for="native-note">Your real debugger observations, when available</label><textarea id="native-note" rows="5" maxlength="10000">${esc(r.nativeNote)}</textarea>${button('next-lesson','Continue to the next idea →','primary')}</article>`;
 const i=Math.min(vmStep,g.steps.length-1),s=g.steps[i];return `<article class="lesson-card"><span class="eyebrow">REAL WINDOWS PRACTICE · ORIGINAL OBSERVATION LAB</span><h2>${esc(g.title)}</h2><p>${esc(g.goal)}</p><p class="notice">Use the separate v0.2 lab pack in a disposable Windows VM. These are safe observation exercises, not native exploit challenges. Commands below are original lab instructions.</p><div class="worked-step"><span class="step-number">${i+1}/${g.steps.length}</span><div><h3>${esc(s[0])}</h3><pre>${esc(s[1])}</pre><p><b>What to expect:</b> ${esc(s[2])}</p></div></div><div class="bottom-actions">${button('vm-back','← Previous',i===0?'invisible':'')}${button('vm-next',i+1===g.steps.length?'Back to the first step':'Next action →','primary')}</div><details><summary>Before leaving the VM, answer this</summary><p>${esc(g.question)}</p></details><label for="native-note">Observed addresses / values and explanation (self-reported)</label><textarea id="native-note" rows="4" maxlength="10000" placeholder="I observed… This supported / contradicted my prediction because…">${esc(r.nativeNote)}</textarea><p class="small">These notes are not automatically graded. The SEH guide’s gn behavior is based on Microsoft’s Go with Exception Not Handled documentation; it is an explicitly labelled supplement to the course map.</p></article>`;}
function review(){const q=S.teaching.review,dues=dueLessons(S);return title('REVIEW WHAT YOU HAVE LEARNED','A small check, not a surprise exam.','Only completed concept lessons enter this review queue.')+(q?`<article class="lesson-card"><h3>${esc(lessonById(q.id).title)}</h3>${practice(lessonById(q.id),q.trial,'review',true)}${q.recorded?button('end-review','Back to due reviews →','primary'):''}</article>`:`<article class="lesson-card"><h2>${dues.length?`${dues.length} concepts are due`:'No concepts are due right now'}</h2><p>${dues.length?'Each check uses a new generated case.':'Finish one lesson first. New advanced topics will not appear out of nowhere.'}</p>${dues.slice(0,5).map(l=>`<button class="review-row" data-review-id="${l.id}">${esc(l.title)} <span>Review →</span></button>`).join('')}${button('home','Return to learning')}</article>`);}
function coverage(){const items=sourceIndex.filter(x=>!sourceFilter||x.chapter===sourceFilter),direct=x=>lessons.filter(l=>l.sections.includes(x.section));return title('NO HIDDEN GAPS','The PDF is the syllabus, not the interface.','An inventory entry, a taught concept and a completed native exercise are different things.')+`<div class="stats"><div><b>${lessons.length}</b><span>short concept lessons</span></div><div><b>${sourceIndex.length}</b><span>source headings indexed</span></div><div><b>5</b><span>original WinDbg walkthroughs</span></div></div><p class="notice">This release teaches core concepts across all 13 chapters. It does NOT claim to convert every case-study step or the ${sourceIndex.filter(s=>s.type==='exercise').length} exercise/extra-mile groups into finished native labs. Those remain explicitly pending below.</p><label for="source-filter">Focus on one chapter</label><select id="source-filter"><option value="0">All chapters</option>${chapters.slice(1).map((t,i)=>`<option value="${i+1}" ${sourceFilter===i+1?'selected':''}>${i+1} · ${esc(t)}</option>`).join('')}</select><div class="coverage-list">${items.map(x=>{const related=direct(x),exercise=x.type==='exercise';return `<article><div><span class="small">§${esc(x.section)} · p. ${x.page}</span><h3>${esc(x.title)}</h3></div><div>${tag(exercise?'Native exercise conversion pending':related.length?'Related concept lesson available':x.type==='reference'?'Source reference / dated administration':'Detailed teaching conversion pending')}${!exercise?related.map(l=>`<button class="text" data-lesson="${l.id}">Learn: ${esc(l.title)} →</button>`).join(''):''}</div></article>`;}).join('')}</div>`;}
function journal(){const records=Object.entries(S.teaching.records),completed=records.filter(([,r])=>r.completed);return title('YOUR EVIDENCE','Keep explanations, not just completion marks.','Previous v0.1 notes, sessions and attempts are preserved separately.')+`<div class="stats"><div><b>${completed.length}</b><span>concept checks passed</span></div><div><b>${records.filter(([,r])=>r.nativeNote.trim()).length}</b><span>self-reported VM notes</span></div><div><b>${S.attempts.length}</b><span>legacy lab attempts kept</span></div></div><section class="lesson-card"><h2>Log a study session</h2><form id="session-form"><label>Topic<input name="topic" maxlength="180" value="${esc(lesson().title)}" required></label><label>Minutes<input type="number" name="minutes" min="1" max="720" value="20" required></label><button class="primary">Save session</button></form></section>${records.filter(([,r])=>r.reflection||r.nativeNote).map(([id,r])=>`<article class="lesson-card"><h2>${esc(lessonById(id).title)}</h2>${tag(r.completed?'Concept check passed':'In progress')}<p class="pre">${esc(r.reflection||'No reflection yet.')}</p>${r.nativeNote?`<details><summary>Windows observations · self-reported</summary><p class="pre">${esc(r.nativeNote)}</p></details>`:''}<button data-lesson="${id}">Revisit lesson</button></article>`).join('')}<details class="lesson-card"><summary>Previous chapter notes and study sessions</summary>${Object.entries(S.chapters).map(([id,c])=>`<h3>Chapter ${id} · ${esc(c.stage)}</h3><p class="pre">${esc(c.note||'No note.')}</p>`).join('')}${S.sessions.slice(-20).reverse().map(s=>`<p>${esc(s.date)} · ${s.minutes} min · ${esc(s.topic)}</p>`).join('')}<p class="small">All legacy attempts, quizzes, chapter states and timer data remain in the full backup. They are not silently counted as new lesson mastery.</p></details>`;}
function settings(){return title('YOUR LOCAL WORKSPACE','Keep your data and your real deadlines.','No API key, cloud account or live AI service is needed for these authored lessons.')+`<div class="settings-grid"><form class="lesson-card" id="settings-form"><h2>Study schedule</h2><label>Name<input name="name" maxlength="60" required value="${esc(S.settings.name)}"></label><label>Start date<input name="startDate" type="date" required value="${esc(S.settings.startDate)}"></label><label>Hours per week<input name="weeklyHours" type="number" min="1" max="60" step="0.5" value="${S.settings.weeklyHours}" required></label><label>Actual lab start<input name="labStart" type="date" value="${esc(S.settings.labStart)}"></label><label>Actual lab expiry<input name="labEnd" type="date" value="${esc(S.settings.labEnd)}"></label><label>Actual exam expiry<input name="examExpiry" type="date" value="${esc(S.settings.examExpiry)}"></label><button class="primary">Save settings</button><p class="small">The proposed study duration does not extend provider access. Dates must come from your account.</p></form><section class="lesson-card"><h2>Backup and privacy</h2><p>Lessons, reflections and observations save on this device. There is no live phone sync or background notification service.</p>${button('export','Export complete backup','primary')}<label class="file-label">Import a backup<input id="import" type="file" accept=".json,application/json"></label><p class="notice">Import replaces, not merges, progress. A valid backup is checked before confirmation. Export first. After using v0.2, do not run the older v0.1 executable against the same journal.</p><h3>Your optional PDF reference</h3><p>The original course stays on your PC. The lessons are readable without linking it.</p>${native?button('select-pdf',info.pdf?`Linked: ${esc(info.pdf)} · Change`:'Link my local PDF'):'<p class="small">Linking a local PDF is supported by the Windows EXE. Browser preview keeps only local progress.</p>'}<p class="small">Database: ${esc(info.database||'browser IndexedDB')}</p></section></div>`;}
function render(){if(!S)return;$('#app').innerHTML=top()+menuHTML()+`<main id="main" tabindex="-1">${({learn,review,coverage,journal,settings})[view]()}</main>`;}
function move(step){record().step=step;render();save().catch(error);window.scrollTo(0,0);}
async function action(a){const r=record(),l=lesson();switch(a){
 case 'home':view='learn';break;
 case 'menu':menu=!menu;break;
 case 'watch':move(1);return;
 case 'watch-next':r.watch=Math.min(r.watch+1,exercise(l.kind,l.id+':worked').steps.length-1);break;
 case 'watch-back':r.watch=Math.max(0,r.watch-1);break;
 case 'guided':move(2);return;
 case 'solo':move(3);return;
 case 'remember':move(4);return;
 case 'windows':move(5);return;
 case 'hint':{const t=r[r.step===2?'guided':'solo'];if(r.completed)return;t.hints=Math.min(3,t.hints+1);break;}
 case 'reveal':if(!r.completed)r[r.step===2?'guided':'solo'].revealed=true;break;
 case 'fresh-guided':case 'fresh-solo':retry(r,a.slice(6),uid(),l.kind);break;
 case 'complete':r.reflection=$('#reflection')?.value||r.reflection;complete(r);toast('Concept check saved. Real Windows practice remains separate.');break;
 case 'next-lesson':{const next=lessons[Math.min(l.order+1,lessons.length-1)];S.teaching.selected=next.id;ensureRecord(S,next.id,uid());vmStep=0;view='learn';window.scrollTo(0,0);break;}
 case 'vm-back':vmStep=Math.max(0,vmStep-1);break;
 case 'vm-next':vmStep=(vmStep+1)%guideFor(l).steps.length;break;
 case 'end-review':S.teaching.review=null;break;
 case 'export':await exportData(S);toast('Backup export requested.');return;
 case 'select-pdf':info.pdf=await invoke('select_pdf');break;
 case 'pdf':await invoke('open_pdf');toast(`Reference only: navigate to page ${l.pages[0]}, §${l.sections[0]}.`);return;
 default:return;
 }render();await save();}
document.addEventListener('click',async ev=>{const b=ev.target.closest('button');if(!b||!S||busy)return;try{busy=true;
 if(b.dataset.action)await action(b.dataset.action);
 else if(b.dataset.view){view=b.dataset.view;menu=false;render();window.scrollTo(0,0);}
 else if(b.dataset.lesson){S.teaching.selected=b.dataset.lesson;ensureRecord(S,b.dataset.lesson,uid());menu=false;view='learn';vmStep=0;render();await save();window.scrollTo(0,0);}
 else if(b.dataset.step!==undefined)move(Number(b.dataset.step));
 else if(b.dataset.reviewId){startReview(S,b.dataset.reviewId,uid());render();await save();}
 }catch(err){error(err);}finally{busy=false;}});
document.addEventListener('input',ev=>{if(ev.target.id==='lesson-search'){filter=ev.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{const start=ev.target.selectionStart;render();const s=$('#lesson-search');s.focus();s.setSelectionRange(start,start);},180);}});
document.addEventListener('change',async ev=>{if(!S)return;const t=ev.target;try{
 if(t.id==='chapter-filter'){chapterFilter=Number(t.value);render();}
 if(t.id==='source-filter'){sourceFilter=Number(t.value);render();}
 if(t.id==='reflection'){record().reflection=t.value;await save();}
 if(t.id==='native-note'){record().nativeNote=t.value;await save();}
 if(t.id==='import'&&t.files[0]){if(t.files[0].size>4*1024*1024)throw new Error('Backup exceeds the 4 MiB limit.');const candidate=normalize(JSON.parse(await t.files[0].text()));if(!confirm('Replace this device’s progress with the validated backup? Export your current progress first.'))return;await persist(candidate);S=candidate;pauseOnLoad(S.timer);render();toast('Backup imported.');}
 }catch(err){error(err);}});
document.addEventListener('submit',async ev=>{ev.preventDefault();if(!S||busy)return;try{busy=true;const f=ev.target,d=new FormData(f);
 if(f.id==='answer-form'){const a=String(d.get('answer')??'');if(f.dataset.review==='true')answerReview(S,a);else submit(record(),f.dataset.part,lesson().kind,a);}
 if(f.id==='settings-form'){const candidate=structuredClone(S);for(const[k,v]of d.entries())candidate.settings[k]=k==='weeklyHours'?Number(v):v;S=normalize(candidate);}
 if(f.id==='session-form'){S.sessions.push({id:uid(),date:day(),minutes:Number(d.get('minutes')),topic:String(d.get('topic'))});S=normalize(S);toast('Study session saved.');}
 await save();render();
 }catch(err){error(err);}finally{busy=false;}});
(async()=>{try{S=await load();pauseOnLoad(S.timer);ensureRecord(S,S.teaching.selected,uid());if(native)info=await invoke('app_info');render();await save();if(native&&info.uiSmoke){const x=exercise('stack','native-startup');await invoke('smoke_report',{ok:lessons.length===57&&sourceIndex.length===375&&!!$('#main .lesson-card')&&check(x,String(x.answer))&&normalize(S).teaching.version===1});}if(!native&&'serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}catch(err){$('#app').innerHTML=`<main class="fatal"><h1>Your journal was not overwritten.</h1><p>${esc(err.message)}</p><p>Restart the app or restore a known-good backup. Keep your existing database file.</p></main>`;if(native)invoke('smoke_report',{ok:false}).catch(()=>{});}})();
