/* Original teaching explanations. References locate concepts in the user's EXP-301 v1.0 PDF.
   Numbers, snapshots, mini-labs and wording below are new; no vendor solution is bundled. */
const rows = [
['welcome',1,'Start with one thing, not 604 pages','1.3.2 1.3.3',[17,18],'workflow',
'You do not need to understand an entire exploit today. A lesson here gives you one small idea, shows it happening, and lets you try it with different numbers. The original course uses exercises to consolidate understanding before progressing.',
'Think of learning to drive: first learn what one control changes; later combine controls in traffic. Reading the dashboard labels is not the same as driving.',
'Use Learn for an explanation, Watch for a worked example, Guided for supported practice, and Solo for a new problem. A passed simulation is reasoning practice, not proof that you can exploit a Windows program.',
'Finish one lesson, write what changed in your own words, then do its Windows practice when you have the VM available. Reading the source is optional reinforcement, not the first step.'],
['bytes',2,'A byte is a value; an address is a place','2.1.1 2.3.2',[21,21],'byte',
'A byte holds eight bits. We write its value using two hexadecimal digits: 0x2A is the number 42. The 0x prefix only tells you the number is written in base sixteen. An address tells you where a byte is stored; it is not automatically the value stored there.',
'A numbered locker is the address. The item inside it is the value. Locker 42 can contain the number 7; its contents do not have to match its label.',
'In the worked example, first point to the address column, then the value column. Say “at this address, the byte contains this value.” This one distinction will make debugger output much less intimidating.',
'This is an original prerequisite bridge into the memory concepts on page 21 and memory displays on pages 32–35. You are not expected to know a debugger command yet.'],
['endian',3,'Why four bytes can look backwards','3.4.6',[80,80],'endian',
'A 32-bit value occupies four bytes. In x86 little-endian storage, the least-significant byte goes at the lowest address. For 0x12345678 the bytes, from lowest to highest address, are 78 56 34 12. The digits inside each byte are not reversed.',
'Imagine four numbered envelopes. Put the smallest-place-value piece in the first envelope. You reorder the envelopes, not the characters printed on each piece.',
'The CPU register still displays the number as 0x12345678. A byte dump shows the four storage pieces. Both views describe the same value. This is why copying an address as text is different from packing its bytes.',
'This page-80 concept is deliberately introduced early as a bridge. For now, practice four-byte storage only; exploit return addresses come later.'],
['pointers',2,'A pointer means: look over there','2.1.2.2 2.3.2',[24,24],'pointer',
'A pointer is a value used as a memory address. If EAX contains 0x2000, EAX holds 0x2000. If the four bytes at address 0x2000 represent 7, reading through that pointer produces 7. These are two different operations.',
'A contact card contains a house address. Reading the card gives you the address. Going to the house gives you what is there. Dereferencing is that second action.',
'For a four-byte load, MOV ECX, EAX copies the register value. MOV ECX, [EAX] reads memory at the address in EAX. The brackets change the meaning. Our practice memory is explicitly fictional and mapped.',
'First answer what the pointer contains. Only then answer what the pointed-to memory contains. Do not guess that every number is a valid address.'],
['registers',2,'Registers: the CPU’s small working spaces','2.1.2 2.1.2.1',[23,24],'register',
'A register is a small storage location inside the CPU. In this course’s 32-bit setting, EAX can hold a 32-bit value. AX names its lower 16 bits; AL and AH name the low and next byte. These are overlapping views, not independent storage boxes.',
'Picture a four-compartment tray. EAX is the whole tray. AX is the lower two compartments. AL and AH each select one of those compartments.',
'When you read AL, keep only the rightmost byte of EAX. Reading AH selects the next byte. A change to a subregister changes that part of its parent register. Start with reading the views before attempting edits.',
'The PDF’s register diagram on page 23 motivates this lesson. Today you only need EAX, AX, AH and AL; do not memorise every register at once.'],
['stack',2,'PUSH and POP: watch the stack move','2.1.1.1 2.1.2.2',[22,24],'stack',
'The stack is a thread’s short-term storage for function data and control information. Last in, first out means the most recently pushed item is popped first. ESP is the address of the current stack top, not the data stored at that top.',
'Think of stacking plates, but our address labels count downward when a new 32-bit item is pushed. The plate and the shelf label are different things.',
'In this lesson all operands and stack slots are 32-bit. Each PUSH subtracts four from ESP and stores one value. Each POP reads the top value and adds four to ESP. We trace one instruction at a time.',
'Watch both the ESP number and the occupied memory cells. A POP changes the logical top; it does not need to wipe the old bytes to remove the item from the active stack.'],
['returns',2,'How a function knows where to return','2.1.1.3 2.1.2.4',[22,24],'return',
'When code calls a function, it needs a way back. The saved return address identifies the instruction after the call. In this simplified near-CALL/RET model, that address is saved on the stack, and RET later loads it into EIP.',
'You put a bookmark in your current chapter before checking an appendix. The bookmark is not the appendix’s address; it identifies where you resume afterward.',
'EIP tells us which instruction is next. ESP tells us where the current stack top is. Before RET, read the return-address value at the stack top. After RET, that value is the new EIP and ESP has moved by four.',
'This exercise assumes a plain RET, no immediate cleanup and a correctly restored stack. Extra cleanup and corrupted frames are separate lessons.'],
['frames',2,'EBP gives a function a reference point','2.1.2.3 2.1.1.2',[22,24],'frame',
'A stack frame groups information for one function call. ESP moves as temporary values are pushed. In the conventional frame used by this lesson, PUSH EBP saves the old frame pointer and MOV EBP, ESP creates a stable reference for locating arguments.',
'A moving elevator needs a fixed floor marker. EBP is our reference marker; ESP is the position that keeps changing during the function’s work.',
'For our stated frame layout, saved EBP is at [EBP], the return address at [EBP+4], and the first four-byte argument at [EBP+8]. Every following four-byte argument is four bytes further along.',
'This is an explicit teaching layout, not a promise that every compiler emits the same frame. In a real binary, inspect its prologue before using these offsets.'],
['debugger',2,'Pause, look, and continue','2.2.1 2.2.2 2.2.3',[25,28],'debugger',
'A debugger lets you inspect a running program and control when it executes. After attaching, the program can be paused. That does not automatically mean it is broken: it may simply be waiting for you to allow execution to continue.',
'Think of a video you can pause, inspect frame by frame, and play again. The paused video is not a frozen television.',
'In the course workflow, g continues execution. The Command window accepts debugger commands and the Disassembly view shows instructions. Learn these two views first instead of configuring every available panel.',
'The command practice is a simulation. The Windows lab tab gives the corresponding actions in real WinDbg, so you can connect a familiar idea to the actual tool.'],
['symbols',2,'Symbols turn addresses into names','2.2.4',[30,31],'symbols',
'Debugging symbols give names and type information to addresses and memory layouts. A PDB can help WinDbg show function names, structures and variables instead of only numbers. A missing PDB does not itself prove that the program has a memory-corruption bug.',
'A map with street names is easier to follow than the same map with coordinates only. Symbols add the labels; they do not repair the roads.',
'The course uses a configured symbol path and .reload /f to load available symbols. For our original lab, use its matching PDB beside the executable. The exact executable and PDB must be kept together.',
'When names are unavailable, keep the address and module identity in your notes. Do not treat a symbol-loading message as the root cause of every crash.'],
['dump',2,'Read the same memory as bytes or DWORDs','2.3.1 2.3.2',[32,35],'dump',
'db shows bytes. dw shows two-byte words. dd shows four-byte DWORDs. These commands change the display grouping, not the stored memory. The L count is a count of displayed elements, so four DWORDs cover sixteen bytes.',
'The same twelve eggs can be shown as twelve singles or three groups of four. Regrouping the display does not add or remove eggs.',
'Use a short range so you can explain every value. In our practice, L0n3 explicitly requests three elements in decimal. “dd ADDRESS L0n3” therefore displays twelve bytes. The u command instead interprets memory as instructions.',
'Before executing a display command, predict how many bytes it will cover. Then compare a byte view and a DWORD view of the same location.'],
['dereference',2,'Follow a pointer one step at a time','2.3.2',[35,36],'dereference',
'poi(ADDRESS) reads a pointer-sized value stored at ADDRESS. In our 32-bit process, that means four bytes. dd poi(ADDRESS) first gets that pointer value, then displays memory at the pointed-to location.',
'A note sends you to a locker. The locker contains another address. Follow one instruction at a time rather than jumping directly to the final object.',
'Write the chain as ADDRESS → stored pointer → final data. Each arrow represents a memory read. When the chain is wrong, locate the first invalid or unexpected read instead of blaming the last command.',
'The worked memory table supplies every mapped location. Actual memory may be unmapped or unreadable; a pointer-looking value alone is not permission to read it.'],
['structures',2,'Structures are fields at offsets','2.3.3',[36,38],'structure',
'A structure groups fields. Each field has an offset from the structure’s beginning and a type. dt TYPE describes a type layout; dt TYPE ADDRESS also interprets the data at an address using that layout, when the required symbols are available.',
'A form has labelled boxes. Knowing where the form starts is not enough: you also need each box’s position and what kind of value belongs there.',
'For a field at offset 0x08 and a structure at 0x3000, its address is 0x3008. If that field is a pointer, you still need another read to get to what it points at. Offset arithmetic and dereferencing are separate.',
'Our mini-lab supplies the field layout. Never assume a structure layout is universal across architectures or versions; use the matching information for the debugged process.'],
['edit',2,'Editing memory is not editing a register','2.3.4 2.3.6',[38,41],'edit',
'ed ADDRESS VALUE changes a DWORD in memory. r eax=VALUE changes the EAX register. If EAX points to memory, changing EAX changes the pointer; it does not overwrite the object at the old address.',
'Changing a delivery label is different from replacing the parcel’s contents. Both matter, but they are not interchangeable.',
'Use the smallest edit needed, predict the affected location, then read it back. The worked snapshot separates the command, the register and the old pointed-to memory. Nothing is written to a real process inside this simulator.',
'When doing the VM exercise, edit only the deliberately provided lab variable. Do not practise arbitrary memory writes against unrelated applications or your study tracker.'],
['search',2,'Find data before following its code','2.3.5',[39,40],'search',
'A memory search looks for a pattern in a range. The pattern’s representation matters: a sequence of bytes, an ASCII string and a Unicode string are not the same request. Searching first gives you candidate locations to inspect.',
'Finding a word in a book is not the same as finding it in an index encoded with different letters. Choose the representation that matches the stored data.',
'The course uses s with a type, range and pattern. Here we search a tiny byte array so you can see every match. A match is evidence that the bytes are present; it is not proof they are the only active copy.',
'Our toy uses a fixed byte array. In the VM, search a known lab buffer rather than the entire address space at first; then inspect a returned address.'],
['breakpoints',2,'Stop at the instruction you care about','2.4.1',[41,43],'breakpoint',
'A breakpoint requests a pause at a chosen point in execution. bp sets a software breakpoint. bl lists breakpoints, bd disables one, be enables one, and bc removes one. Setting it is only preparation; the program still has to reach it.',
'Putting a speed camera on one street does not guarantee a particular car will pass it. The trigger depends on the route the car actually takes.',
'Set one meaningful breakpoint, continue with g, and perform the action that should reach it. If it does not trigger, check your path hypothesis instead of randomly adding dozens more.',
'The practice asks which operation matches your intention. The Windows lab uses our own named functions, not a hard-coded address from a screenshot.'],
['deferred',2,'An unresolved breakpoint can be waiting, not broken','2.4.2',[43,45],'deferred',
'bu records a breakpoint by an unresolved symbol. This is useful when its module has not loaded yet. The debugger can resolve it later when the module becomes available. Resolved and triggered describe different events.',
'You schedule a delivery to a shop that has not opened. The address becoming available does not mean the parcel has already been delivered.',
'First ask whether the module is loaded, then whether the symbol resolves, then whether execution actually reaches it. The course demonstrates that resolving a breakpoint alone does not mean it was hit.',
'Keep these three observations separate in your notes. This prevents spending time debugging code that never ran.'],
['conditional',2,'Pause only when a useful condition is true','2.4.3',[45,47],'conditional',
'A breakpoint action can inspect data when the breakpoint triggers. A conditional breakpoint continues past uninteresting cases and stops when a condition matches. This turns “pause constantly” into “pause when the relevant input is handled.”',
'A door counter becomes more useful when it tells you only when a particular ticket number arrives. You avoid inspecting every visitor.',
'The course combines breakpoint actions, .printf, .if and .else. Our mini-lab first teaches the decision: inspect an argument, compare it to the target, then stop or continue. Command punctuation comes after the decision makes sense.',
'In a real session, verify where the argument lives before testing it. A perfectly written condition at the wrong stack offset still checks the wrong value.'],
['watchpoint',2,'Catch the code that changes a value','2.4.4',[47,50],'watchpoint',
'A hardware data breakpoint watches access to a memory location. The course’s ba w example stops when data is written. This is useful when you know which data changed but do not yet know which code changed it.',
'Rather than watching every worker in a building, put a sensor on the drawer you care about. The next change leads you to the responsible activity.',
'Choose the address and size of the field to watch. In the course example, the debugger stops after the instruction that wrote the data, so inspect the preceding instruction as well. Do not assume EIP always points at the writer itself.',
'Our watchpoint simulation selects the first overlapping write. It is a reasoning model, not a full implementation of processor debug registers.'],
['stepping',2,'Step into versus step over','2.4.5',[50,52],'stepping',
'p steps over and t steps into. At a call, step-into lets you examine the called function; step-over runs through it and stops afterward under normal completion. The called function still executes when you step over it.',
'You can inspect a delivery route stop by stop or wait for the courier to return. Waiting for the return does not cancel the deliveries.',
'Choose t when the called function may contain the behavior you need to understand. Choose p when you only need its result. The course also introduces pt for a return and ph for a branch boundary.',
'Practice making the choice before typing commands. The goal is deliberate navigation, not single-stepping every instruction in a large application.'],
['modules',2,'A module base is an anchor, not a function','2.5.1',[52,54],'rebase',
'A process loads an executable and libraries called modules. lm lists modules and their address ranges. x searches symbol names. An offset inside one particular module can identify where code sits relative to that module’s starting address.',
'A hotel can move to a new city while room numbers keep their internal relationship. The street address is the base; the room’s relative position is the offset.',
'For the same module build, runtime address = runtime base + relative virtual address (RVA). If a known symbol is at 0x502000 and its RVA is 0x2000, the base is 0x500000. Never mix offsets from different builds.',
'This is a prerequisite bridge to the rebasing used later. On pages 52–54, concentrate on recognising modules, ranges and symbols.'],
['calculator',2,'Do address arithmetic without switching tools','2.5.2 2.5.3 2.5.4',[54,56],'arithmetic',
'WinDbg can evaluate expressions with ?. Its default number interpretation in the course is hexadecimal; 0n explicitly marks decimal and 0y binary. Write the prefix when ambiguity would make an offset wrong.',
'Ten centimetres and ten inches use the same digits but different units. Number bases can create a similar silent misunderstanding.',
'Pseudo-registers such as $t0 are debugger variables, not physical CPU registers. They let you name intermediate calculations. Split a long expression into smaller results and check each one before using it.',
'The practice uses explicit hexadecimal or decimal inputs. The matching source focus is just the calculator and pseudo-register pages, not the whole debugger chapter.'],
['bounds',3,'A copy needs a destination that is big enough','3.1',[57,59],'bounds',
'A buffer is a region reserved for data. A copy crosses its boundary when it writes more bytes than the destination holds. The extra bytes may change nearby data. A crash depends on what was overwritten and when that data is used.',
'A tray has a fixed number of slots. Adding more items does not automatically enlarge it; something outside the tray must give way.',
'Our original exercise uses a counted copy: the stated count includes every byte written. Compare that count with capacity. A C string also has a terminating zero byte; count that separately when applying the idea to string copies.',
'The page-58 prose is imprecise at the exact string-capacity boundary. This toy deliberately specifies the total byte count instead of silently reproducing that ambiguity.'],
['offset',3,'Find the exact input bytes that reached a slot','3.4.2',[64,67],'offset',
'A crash showing repeated bytes tells you input reached somewhere important. It does not tell you which input position did it. An offset is the distance from the start of your input to the target slot, measured in bytes.',
'Knowing paint reached a wall is not enough to locate the leaking hole. Number the drops so you can identify where the leak began.',
'The course uses a non-repeating pattern, then confirms the calculated offset with a distinct four-byte marker. Our model gives a numbered input and a target index. You must place the marker exactly, not merely make the data longer.',
'The mini-lab checks a model buffer layout. Actual EIP control still requires observing the real program; a correct arithmetic answer is not an exploit.'],
['badbytes',3,'Find the first byte that changed','3.4.4',[70,72],'badbytes',
'A bad character is contextual: a byte may terminate, transform or otherwise disrupt the particular input path. It is not a universal list to copy into every future exercise. Compare what you sent with what arrived in memory.',
'A postal machine may fold one envelope type while another passes untouched. The problem belongs to the route and packaging, not to all paper everywhere.',
'Start at the first mismatch. Later differences may only be consequences of that first change or truncation. Remove or isolate one suspected byte, repeat, and record which field and processing stage you tested.',
'Our comparison model changes one byte. The source case has its own protocol-dependent constraints; we do not reuse its list for original labs.'],
['redirect',3,'An address is useful only under the right conditions','3.4.5 3.4.6',[72,73],'redirect',
'Having a controlled instruction pointer and having a working execution path are different achievements. The destination must exist, be usable under the relevant mitigations, and survive any input-byte constraints. A changing stack address makes an old hard-coded address unreliable.',
'A key fitting one door yesterday does not establish where the door is today, whether it is locked differently, or whether the key survived the journey.',
'The course separates buffer location from a dependable redirection mechanism. Our exercise asks you to check the assumptions on a fictional candidate instead of selecting an address just because it looks familiar.',
'Use this lesson to explain why a candidate fails. The mini-lab does not execute instructions or locate gadgets in external software.'],
['decoder-space',3,'Code can overwrite the space it is using','3.4.7 3.4.8 3.4.9',[82,86],'workspace',
'Encoded payload bytes need a decoder before they can run. The course shows a decoder using stack space near its own instructions and damaging bytes it still needs. Reaching the buffer is therefore not the last thing to verify.',
'Imagine writing a calculation on a sheet while erasing the part containing your next instruction. Your working area and instructions must not collide.',
'Our model shows two address ranges: bytes needed later and bytes written as workspace. Check whether they overlap. Then move the workspace in the model and repeat. This teaches the failure mechanism without executing a payload.',
'Cleanup and repeatability also matter: the course distinguishes ending one thread from terminating a whole service. Keep that as a separate observation from first-time success.'],
];
export const foundationRows=rows;
