/* Original teaching explanations. References locate concepts in the user's EXP-301 v1.0 PDF.
   Numbers, snapshots, mini-labs and wording below are new; no vendor solution is bundled. */
const rows = [
['welcome',1,'Start with one thing, not 604 pages','1.3.2 1.3.3',[17,18],'workflow',
'You do not need to understand an entire exploit today. Each lesson teaches one small idea, shows an example, and lets you try it with different numbers. The course exercises help you check your understanding before moving on.',
'Think of learning to drive: first learn what one control changes; later combine controls in traffic. Reading the dashboard labels is not the same as driving.',
'Use Learn for an explanation, Watch for a worked example, Guided for supported practice, and Solo for a new problem. A passed simulation is reasoning practice, not proof that you can exploit a Windows program.',
'Finish one lesson, explain what changed in your own words, then do its Windows practice when your virtual machine (VM) is available. Read the source pages when you want more detail.'],
['bytes',2,'A byte is a value; an address is a place','2.1.1 2.3.2',[21,21],'byte',
'A byte holds eight bits. We write its value using two hexadecimal digits: 0x2A is the number 42. The 0x prefix only tells you the number is written in base sixteen. An address tells you where a byte is stored; it is not automatically the value stored there.',
'A numbered locker is the address. The item inside it is the value. Locker 42 can contain the number 7; its contents do not have to match its label.',
'In the worked example, find the address column first, then the value column. Say “at this address, the byte contains this value.” Keeping these two ideas separate makes debugger output easier to read.',
'This original lesson prepares you for memory concepts on page 21 and memory displays on pages 32–35. You do not need to know any debugger commands yet.'],
['endian',3,'Why four bytes can look backwards','3.4.6',[80,80],'endian',
'A 32-bit value takes four bytes. x86 stores it in little-endian order: the least-significant byte, shown on the right of the number, goes at the lowest address. For 0x12345678 the bytes, from lowest to highest address, are 78 56 34 12. Keep the digits inside each byte in the same order.',
'Imagine four numbered envelopes. Put the smallest-place-value piece in the first envelope. You reorder the envelopes, not the characters printed on each piece.',
'The CPU register still displays the number as 0x12345678. A byte dump shows the four storage pieces. Both views describe the same value. This is why copying an address as text is different from packing its bytes.',
'This idea appears on page 80, but learning it early helps with memory displays. Practise storing four bytes first. You will use it with return addresses later.'],
['pointers',2,'A pointer means: look over there','2.1.2.2 2.3.2',[24,24],'pointer',
'A pointer is a value used as a memory address. If EAX contains 0x2000, EAX holds 0x2000. If the four bytes at address 0x2000 represent 7, reading through that pointer produces 7. These are two different operations.',
'A contact card contains a house address. Reading the card gives you the address. Going to the house gives you what is there. Dereferencing is that second action.',
'For a four-byte load, MOV ECX, EAX copies the value in EAX. MOV ECX, [EAX] reads four bytes from the address held in EAX. The brackets mean “read memory here.” All memory locations in this practice are invented and available to read.',
'First answer what the pointer contains. Only then answer what the pointed-to memory contains. Do not guess that every number is a valid address.'],
['registers',2,'Registers: the CPU’s small working spaces','2.1.2 2.1.2.1',[23,24],'register',
'A register is a small storage location inside the CPU. In this 32-bit course, EAX holds a 32-bit value. AX refers to its lower 16 bits. AL refers to its lowest byte, and AH to the next byte. These names select parts of the same stored value.',
'Picture a four-compartment tray. EAX is the whole tray. AX is the lower two compartments. AL and AH each select one of those compartments.',
'When you read AL, keep only the rightmost byte of EAX. Reading AH selects the next byte. A change to a subregister changes that part of its parent register. Start with reading the views before attempting edits.',
'The register diagram is on page 23. For this lesson, focus on EAX, AX, AH and AL. Learn the other registers when you need them.'],
['stack',2,'PUSH and POP: watch the stack move','2.1.1.1 2.1.2.2',[22,24],'stack',
'The stack is a thread’s short-term storage for function data and control information. Last in, first out means the most recently pushed item is popped first. ESP is the address of the current stack top, not the data stored at that top.',
'Think of stacking plates, but our address labels count downward when a new 32-bit item is pushed. The plate and the shelf label are different things.',
'In this lesson all operands and stack slots are 32-bit. Each PUSH subtracts four from ESP and stores one value. Each POP reads the top value and adds four to ESP. We trace one instruction at a time.',
'Watch the ESP value and the memory cells holding data. A POP moves the active stack top. The old bytes can remain in memory even though they are no longer part of the active stack.'],
['returns',2,'How a function knows where to return','2.1.1.3 2.1.2.4',[22,24],'return',
'When code calls a function, it needs a way back. The saved return address identifies the instruction after the call. In this simplified near-CALL/RET model, that address is saved on the stack, and RET later loads it into EIP.',
'Before looking at another page, you mark your current place with a bookmark. The bookmark tells you where to continue when you come back.',
'EIP tells us which instruction is next. ESP tells us where the current stack top is. Before RET, read the return-address value at the stack top. After RET, that value is the new EIP and ESP has moved by four.',
'This exercise assumes a plain RET, no immediate cleanup and a correctly restored stack. Extra cleanup and corrupted frames are separate lessons.'],
['frames',2,'EBP gives a function a reference point','2.1.2.3 2.1.1.2',[22,24],'frame',
'A stack frame holds information for one function call. ESP moves when temporary values are pushed. In this lesson, PUSH EBP saves the old frame pointer. MOV EBP, ESP then copies the current stack position into EBP. EBP gives us a fixed point for finding the arguments.',
'A moving elevator needs a fixed floor marker. EBP is our reference marker; ESP is the position that keeps changing during the function’s work.',
'For our stated frame layout, saved EBP is at [EBP], the return address at [EBP+4], and the first four-byte argument at [EBP+8]. Every following four-byte argument is four bytes further along.',
'This is the layout used in our example. Compilers can create other layouts. In a real program, inspect the function prologue, the instructions that set up its frame, before using these offsets.'],
['debugger',2,'Pause, look, and continue','2.2.1 2.2.2 2.2.3',[25,28],'debugger',
'A debugger lets you inspect a running program and control when it executes. After attaching, the program can be paused. That does not automatically mean it is broken: it may simply be waiting for you to allow execution to continue.',
'Think of a video you can pause, inspect frame by frame, and play again. The paused video is not a frozen television.',
'In the course workflow, g continues execution. The Command window accepts debugger commands and the Disassembly view shows instructions. Learn these two views first instead of configuring every available panel.',
'The command practice is a simulation. The Windows lab tab gives the matching steps in real WinDbg so you can practise the same idea with the actual tool.'],
['symbols',2,'Symbols turn addresses into names','2.2.4',[30,31],'symbols',
'Debugging symbols connect addresses to names and describe data types. A Program Database (PDB) file can help WinDbg show function names, structures and variables. Without it, you may see only addresses. A missing PDB alone does not prove that the program has a memory-corruption bug.',
'A map with street names is easier to follow than the same map with coordinates only. Symbols add the labels; they do not repair the roads.',
'The course uses a configured symbol path and .reload /f to load available symbols. For our original lab, use its matching PDB beside the executable. The exact executable and PDB must be kept together.',
'When names are unavailable, keep the address and module identity in your notes. Do not treat a symbol-loading message as the root cause of every crash.'],
['dump',2,'Read the same memory as bytes or DWORDs','2.3.1 2.3.2',[32,35],'dump',
'db shows bytes. dw shows two-byte words. dd shows four-byte DWORDs. These commands change the display grouping, not the stored memory. The L count is a count of displayed elements, so four DWORDs cover sixteen bytes.',
'The same twelve eggs can be shown as twelve singles or three groups of four. Regrouping the display does not add or remove eggs.',
'Use a short range so you can explain every value. Here, L0n3 means three elements, with 0n marking a decimal number. “dd ADDRESS L0n3” displays three DWORDs, or twelve bytes. The u command reads the bytes as instructions instead.',
'Before executing a display command, predict how many bytes it will cover. Then compare a byte view and a DWORD view of the same location.'],
['dereference',2,'Follow a pointer one step at a time','2.3.2',[35,36],'dereference',
'poi(ADDRESS) reads a pointer-sized value stored at ADDRESS. In our 32-bit process, that means four bytes. dd poi(ADDRESS) first gets that pointer value, then displays memory at the pointed-to location.',
'A note sends you to a locker. The locker contains another address. Follow one instruction at a time rather than jumping directly to the final object.',
'Write the chain as ADDRESS → stored pointer → final data. Each arrow represents a memory read. When the chain is wrong, locate the first invalid or unexpected read instead of blaming the last command.',
'The example table includes every memory location you need. In a real process, an address may be unmapped or unreadable. A value that looks like a pointer does not prove that its memory can be read.'],
['structures',2,'Structures are fields at offsets','2.3.3',[36,38],'structure',
'A structure groups related fields. Each field has a type and an offset, its distance from the start of the structure. With the required symbols loaded, dt TYPE shows the field layout. dt TYPE ADDRESS also displays the data at that address using the layout.',
'A form has labelled boxes. Knowing where the form starts is not enough: you also need each box’s position and what kind of value belongs there.',
'For a field at offset 0x08 and a structure at 0x3000, its address is 0x3008. If that field is a pointer, you still need another read to get to what it points at. Offset arithmetic and dereferencing are separate.',
'Our mini-lab gives you the field layout. Real layouts can change across processor architectures and software versions. Use the layout that matches the process you are debugging.'],
['edit',2,'Editing memory is not editing a register','2.3.4 2.3.6',[38,41],'edit',
'ed ADDRESS VALUE changes a DWORD in memory. r eax=VALUE changes the EAX register. If EAX points to memory, changing EAX changes the pointer; it does not overwrite the object at the old address.',
'Changing a delivery address sends you to a different place. Changing what is inside a parcel changes its contents. Updating a pointer and updating memory work in the same two ways.',
'Use the smallest edit needed, predict the affected location, then read it back. The worked snapshot separates the command, the register and the old pointed-to memory. Nothing is written to a real process inside this simulator.',
'When doing the VM exercise, edit only the deliberately provided lab variable. Do not practise arbitrary memory writes against unrelated applications or your study tracker.'],
['search',2,'Find data before following its code','2.3.5',[39,40],'search',
'A memory search looks for a pattern within an address range. Choose how to represent that pattern: as bytes, an ASCII string or a Unicode string. These choices can search for different bytes. Inspect the addresses returned by the search.',
'Finding a word in a book is not the same as finding it in an index encoded with different letters. Choose the representation that matches the stored data.',
'The course uses s with a type, range and pattern. Here we search a tiny byte array so you can see every match. A match is evidence that the bytes are present; it is not proof they are the only active copy.',
'Our toy uses a fixed byte array. In the VM, search a known lab buffer rather than the entire address space at first; then inspect a returned address.'],
['breakpoints',2,'Stop at the instruction you care about','2.4.1',[41,43],'breakpoint',
'A breakpoint requests a pause at a chosen point in execution. bp sets a software breakpoint. bl lists breakpoints, bd disables one, be enables one, and bc removes one. Setting it is only preparation; the program still has to reach it.',
'Putting a speed camera on one street does not guarantee a particular car will pass it. The trigger depends on the route the car actually takes.',
'Set one breakpoint that tests your prediction. Continue with g and perform the action that should reach it. If it does not trigger, check whether the program took the path you expected.',
'The practice asks which operation matches your intention. The Windows lab uses our own named functions, not a hard-coded address from a screenshot.'],
['deferred',2,'An unresolved breakpoint can be waiting, not broken','2.4.2',[43,45],'deferred',
'bu records a breakpoint using a symbol name, even when its module has not loaded yet. The debugger can find the address when the module loads. A resolved breakpoint has a known address. A triggered breakpoint means execution has reached it.',
'You schedule a delivery to a shop that has not opened. The address becoming available does not mean the parcel has already been delivered.',
'First ask whether the module is loaded, then whether the symbol resolves, then whether execution actually reaches it. The course demonstrates that resolving a breakpoint alone does not mean it was hit.',
'Keep these three observations separate in your notes. This prevents spending time debugging code that never ran.'],
['conditional',2,'Pause only when a useful condition is true','2.4.3',[45,47],'conditional',
'A breakpoint action can inspect data when the program reaches the breakpoint. A conditional breakpoint checks a rule, such as whether an argument equals a target value. It stops when the rule matches and lets other cases continue.',
'A door counter becomes more useful when it tells you only when a particular ticket number arrives. You avoid inspecting every visitor.',
'The course combines breakpoint actions, .printf, .if and .else. Our mini-lab first teaches the decision: inspect an argument, compare it to the target, then stop or continue. Command punctuation comes after the decision makes sense.',
'In a real session, verify where the argument lives before testing it. A perfectly written condition at the wrong stack offset still checks the wrong value.'],
['watchpoint',2,'Catch the code that changes a value','2.4.4',[47,50],'watchpoint',
'A hardware data breakpoint watches access to a memory location. The course’s ba w example stops when data is written. This is useful when you know which data changed but do not yet know which code changed it.',
'Rather than watching every worker in a building, put a sensor on the drawer you care about. The next change leads you to the responsible activity.',
'Choose the address and size of the field to watch. In the course example, the debugger stops after the instruction that wrote the data. Check the instruction just before EIP as well; EIP may already point to the next instruction.',
'Our watchpoint simulation selects the first overlapping write. It is a reasoning model, not a full implementation of processor debug registers.'],
['stepping',2,'Step into versus step over','2.4.5',[50,52],'stepping',
'p steps over and t steps into. At a call, t lets you inspect the instructions inside the called function. With p, the function still runs, but the debugger normally stops after it returns. Stepping over does not skip the work.',
'You can inspect a delivery route stop by stop or wait for the courier to return. Waiting for the return does not cancel the deliveries.',
'Choose t when the called function may contain the behavior you need to understand. Choose p when you only need its result. The course also introduces pt for a return and ph for a branch boundary.',
'Practice making the choice before typing commands. The goal is deliberate navigation, not single-stepping every instruction in a large application.'],
['modules',2,'A module base is an anchor, not a function','2.5.1',[52,54],'rebase',
'A process loads an executable and libraries called modules. lm lists modules and their address ranges. x searches symbol names. An offset inside one particular module can identify where code sits relative to that module’s starting address.',
'A hotel can move to a new city while room numbers keep their internal relationship. The street address is the base; the room’s relative position is the offset.',
'For the same module build, runtime address = runtime base + relative virtual address (RVA). If a known symbol is at 0x502000 and its RVA is 0x2000, the base is 0x500000. Never mix offsets from different builds.',
'This prepares you for rebasing, which means adjusting addresses when a module loads at another base. For pages 52–54, first learn to recognise modules, address ranges and symbols.'],
['calculator',2,'Do address arithmetic without switching tools','2.5.2 2.5.3 2.5.4',[54,56],'arithmetic',
'WinDbg can calculate expressions directly in the debugger. Use the ? command. In the course setup, numbers default to hexadecimal. Write 0n before a decimal number and 0y before a binary number. A clear prefix helps you avoid calculating with the wrong number base.',
'Ten centimetres and ten inches use the same digits but different units. Number bases can create a similar silent misunderstanding.',
'Pseudo-registers such as $t0 are variables inside the debugger. Use them to save the result of a calculation; they are separate from CPU registers. Break a long calculation into short steps and check each result.',
'The practice uses explicit hexadecimal or decimal inputs. The matching source focus is just the calculator and pseudo-register pages, not the whole debugger chapter.'],
['bounds',3,'A copy needs a destination that is big enough','3.1',[57,59],'bounds',
'A buffer is a region reserved for data. A copy crosses its boundary when it writes more bytes than the destination holds. The extra bytes may change nearby data. A crash depends on what was overwritten and when that data is used.',
'A tray has a fixed number of slots. Adding more items does not automatically enlarge it; something outside the tray must give way.',
'Our original exercise uses a counted copy: the stated count includes every byte written. Compare that count with capacity. A C string also has a terminating zero byte; count that separately when applying the idea to string copies.',
'Page 58 is unclear about the exact limit for a string copy. This model gives the total number of bytes written, including every byte you must count, so the boundary is clear.'],
['offset',3,'Find the exact input bytes that reached a slot','3.4.2',[64,67],'offset',
'A crash showing repeated bytes tells you input reached somewhere important. It does not tell you which input position did it. An offset is the distance from the start of your input to the target slot, measured in bytes.',
'Knowing paint reached a wall is not enough to locate the leaking hole. Number the drops so you can identify where the leak began.',
'The course uses a pattern to find the offset, then checks it with a clear four-byte marker. Our model gives numbered input bytes and a target index. Place the marker at that exact position. Adding more data alone does not confirm the offset.',
'The mini-lab checks a model buffer layout. Actual EIP control still requires observing the real program; a correct arithmetic answer is not an exploit.'],
['badbytes',3,'Find the first byte that changed','3.4.4',[70,72],'badbytes',
'A bad character is a byte that causes a problem on a particular input path. It may end the input, be changed, or affect later bytes. The list depends on the path you test. Compare the bytes you sent with the bytes that arrived in memory.',
'A postal machine may fold one envelope type while another passes untouched. The problem belongs to the route and packaging, not to all paper everywhere.',
'Start at the first mismatch. Later differences may happen because that first byte changed or cut the input short. Test one suspected byte at a time. Repeat the test and record the input field and processing stage you checked.',
'Our comparison model changes one byte. The source case has its own protocol-dependent constraints; we do not reuse its list for original labs.'],
['redirect',3,'An address is useful only under the right conditions','3.4.5 3.4.6',[72,73],'redirect',
'Controlling EIP is one step toward making execution follow your intended path. Check that the destination exists, the active protections allow its use, and its address bytes pass through the input unchanged. If the stack address changes, an address copied from an earlier run may fail.',
'A key fitting one door yesterday does not establish where the door is today, whether it is locked differently, or whether the key survived the journey.',
'The course separates buffer location from a dependable redirection mechanism. Our exercise asks you to check the assumptions on a fictional candidate instead of selecting an address just because it looks familiar.',
'Use this lesson to explain why a candidate fails. The mini-lab does not execute instructions or locate gadgets in external software.'],
['decoder-space',3,'Code can overwrite the space it is using','3.4.7 3.4.8 3.4.9',[82,86],'workspace',
'Encoded payload bytes need a decoder before they can run. The course shows a decoder using stack space near its own instructions and damaging bytes it still needs. Reaching the buffer is therefore not the last thing to verify.',
'Imagine writing a calculation on a sheet while erasing the part containing your next instruction. Your working area and instructions must not collide.',
'Our model shows two address ranges: bytes needed later and bytes written as workspace. Check whether they overlap. Then move the workspace in the model and repeat. This teaches the failure mechanism without executing a payload.',
'Also check what happens afterward and whether you can repeat the result. Ending one thread is different from stopping the whole service. Record these outcomes separately from the first successful run.'],
];
export const foundationRows=rows;
