/* Small, explicitly bounded teaching models. Not a CPU emulator, debugger or exploit grader. */
import {hash} from '../engine.js';
export const hex=n=>'0x'+(n>>>0).toString(16).toUpperCase().padStart(8,'0');
const bytes=n=>Array.from({length:4},(_,i)=>(n>>>(i*8)&255).toString(16).padStart(2,'0')).join(' ');
const table=(headers,rows)=>({headers,rows:rows.map(r=>r.map(String))});
function baseExercise(kind,seed){
 const h=hash(seed),n=2+h%6,b=0x120000+(h%128)*0x100,v=(0x31527496+h)>>>0,k=1+h%3;
 const make=(prompt,answerType,answer,display,steps,explanation,hints=[])=>({kind,seed,prompt,answerType,answer,display,steps,explanation,hints:hints.length?hints:[steps[0],steps[Math.min(1,steps.length-1)]],options:[]});
 const num=(p,a,d,s,x)=>make(p,'number',a,d,s,x);
 const choice=(p,opts,index,d,steps,x)=>({...make(p,'choice',index,d,steps,x),options:opts});
 switch(kind){
 case 'byte':return num(`What BYTE VALUE is stored at address ${hex(b+2)}?`,n,table(['Address (place)','Byte value (contents)'],[[hex(b),hex(n+3)],[hex(b+1),hex(n+1)],[hex(b+2),hex(n)]]),[`Find the row whose address is ${hex(b+2)}.`,`Read the second column, not the row label.`,`That row contains ${n}, written in hexadecimal as ${hex(n)}.`],'An address selects a location; the value column tells you what is stored there.');
 case 'endian':return make(`Write ${hex(v)} as FOUR little-endian bytes, lowest address first.`,'bytes',bytes(v),table(['32-bit number','First byte location'],[[hex(v),hex(b)]]),[`Split the eight hex digits into four byte pairs: ${bytes(v).split(' ').reverse().join(' ')}.`,`Put the least-significant pair at the lowest address.`,`The storage order is ${bytes(v)}. Do not reverse the digits inside each pair.`],'Use exactly four byte pairs separated by spaces. A register number and its byte dump represent the same value.');
 case 'pointer':return num(`After MOV ECX, [EAX], what VALUE is in ECX?`,n*7,table(['Item','Value'],[['EAX',hex(b)],[`DWORD at ${hex(b)}`,n*7]]),[`EAX contains the address ${hex(b)}.`,`Brackets mean read the DWORD at that address.`,`The memory row contains ${n*7}; that becomes ECX.`],'Without brackets, MOV ECX, EAX would copy the address instead.');
 case 'register':return num(`EAX=${hex(v)}. What is the value of AL?`,v&255,table(['View','What it selects'],[['EAX','All 32 bits'],['AX','Lower 16 bits'],['AL','Lowest byte'],['AH','Next byte above AL']]),[`Write EAX as four pairs: ${bytes(v).split(' ').reverse().join(' ')}.`,`AL selects the rightmost pair in the displayed number.`,`That pair is ${(v&255).toString(16).padStart(2,'0')}, which equals ${v&255} in decimal.`],'The byte is part of EAX, not an independent value stored elsewhere.');
 case 'stack':return num('What is ESP after all three instructions?',b-4,table(['Before / instruction','What happens'],[['Initial ESP',hex(b)],['PUSH EAX','32-bit push'],['PUSH EBX','32-bit push'],['POP ECX','32-bit pop']]),[`PUSH EAX: ESP = ${hex(b)} − 4 = ${hex(b-4)}.`,`PUSH EBX: ESP = ${hex(b-8)}.`,`POP ECX: ESP = ${hex(b-8)} + 4 = ${hex(b-4)}.`],'The net effect is one extra four-byte item on the stack. POP does not have to erase the old bytes.');
 case 'return':return num('After a plain RET, what is the new EIP?',b+0x246,table(['Item','Value'],[['ESP before RET',hex(b)],[`DWORD at ${hex(b)}`,hex(b+0x246)]]),[`Read the DWORD at the current ESP (${hex(b)}).`,`Load that VALUE, ${hex(b+0x246)}, into EIP.`,`ESP becomes ${hex(b+4)}. EIP and ESP do different jobs.`],'RET takes the stored destination, not the address of the stack slot containing it.');
 case 'frame':return num(`In this stated conventional frame, where is argument ${k}?`,b+4+4*k,table(['Location','Contents'],[['EBP',hex(b)],['[EBP]','Saved old EBP'],['[EBP+4]','Saved return address'],['[EBP+8]','Argument 1 (four bytes)']]),[`Argument 1 starts at EBP+8.`,`Argument ${k} starts at EBP + 8 + (${k}−1)×4.`,`Its address is ${hex(b+4+4*k)}.`],'This depends on the stated prologue and four-byte arguments; inspect real functions before applying the layout.');
 case 'debugger':return choice('The process is paused after attaching. Which command allows it to continue?', ['g','dd esp','r eax'],0,table(['Observation','Meaning'],[['Debugger prompt is ready','Execution is paused'],['No new application output','Not necessarily a crash']]),['Separate paused execution from a program fault.','g tells the debugger to let execution continue.','Memory and register displays inspect state but do not resume it.'],'Choose an execution-control command, not a display command.');
 case 'symbols':return choice('WinDbg cannot find this program’s PDB. What is the justified conclusion?', ['The program definitely has a buffer overflow','Some names/type details may be unavailable','DEP is disabled'],1,table(['Observed','Not yet observed'],[['Symbol-load warning','Cause of a memory fault']]),['A PDB supplies names and type information.','A load warning concerns the availability of that information.','It does not establish a vulnerability or mitigation setting.'],'Use the matching PDB when available. Keep symbol errors separate from actual fault evidence.');
 case 'dump':return num(`How many bytes are displayed by dd ADDRESS L0n${n}?`,n*4,table(['Token','Meaning'],[['dd','Four bytes per displayed DWORD'],[`L0n${n}`,`${n} elements (explicit decimal)`]]),['dd groups each displayed element into four bytes.',`The count is ${n} elements, not ${n} bytes.`,`${n} × 4 = ${n*4} bytes.`],'Grouping changes how memory is displayed, not the stored memory.');
 case 'dereference':return num(`What first DWORD value does dd poi(${hex(b)}) display in this model?`,n*13,table(['Address','Stored DWORD'],[[hex(b),hex(b+0x100)],[hex(b+0x100),n*13]]),[`poi(${hex(b)}) reads the pointer ${hex(b+0x100)}.`,`dd then displays memory at ${hex(b+0x100)}.`,`The first DWORD there is ${n*13}.`],'There are two reads: get the pointer, then read data from its destination.');
 case 'structure':return num('What is the ADDRESS of the count field?',b+12,table(['Item','Value'],[['Structure base',hex(b)],['count offset','0x0C'],['count field contents',n]]),['A field offset is relative to its containing structure.',`Field address = ${hex(b)} + 0x0C.`,`The address is ${hex(b+12)}. Its contents (${n}) are a different answer.`],'Do not substitute a field’s value when asked where the field lives.');
 case 'edit':{const reg=Boolean(h%2);return num(reg?'After changing EAX, what VALUE remains at its OLD pointed-to address?':'After editing pointed-to memory, what VALUE remains in EAX?',reg?n:b,table(['Object / command','Value'],[['Initial EAX',hex(b)],[`DWORD at ${hex(b)}`,n],['Operation',reg?`r @eax=${hex(b+0x100)}`:`ed @eax 0n${n+5}`]]),['First identify whether the command edits a register or memory.',reg?'r changes the register, not the object at its previous destination.':'ed writes to the destination address but does not replace EAX.',reg?`The old memory value remains ${n}.`:`EAX remains ${hex(b)}.`],'A pointer value and the object it points to are different editable objects.');}
 case 'search':{const at=1+h%3,a=Array.from({length:12},(_,i)=>0x30+i);a[at]=0x61;a[at+1]=0x62;a[8]=0x61;a[9]=0x62;return num('What is the ADDRESS of the FIRST complete 61 62 pattern?',b+at,table(['Byte offset from base','Bytes (in ascending address order)'],[['Base',hex(b)],['0 through 5',a.slice(0,6).map(n=>n.toString(16)).join(' ')],['6 through 11',a.slice(6).map(n=>n.toString(16)).join(' ')]]),['Compare each adjacent pair with 61 62, starting at offset zero.',`The first complete pair begins at offset ${at}; another occurs later.`,`Address = base + offset = ${hex(b+at)}.`],'A first match is not evidence that there are no later copies. Search the stated representation and range.');}
 case 'breakpoint':return choice('You set bp module!function and immediately type bl. Has the function necessarily executed?', ['Yes: setting a breakpoint executes the function','No: bl only lists configured breakpoints','Yes: bl steps into the function'],1,table(['Command','Purpose'],[['bp module!function','Set a breakpoint'],['bl','List breakpoints']]),['Configuration and execution are different events.','Listing the breakpoint proves it was configured.','Resume with g and trigger the relevant application action to test whether it is hit.'],'A breakpoint’s existence does not establish path reachability.');
 case 'deferred':return choice('A deferred breakpoint resolves after a DLL loads. What does that prove?', ['The target address is now resolvable, not necessarily executed','The function has definitely been called','The DLL has no mitigations'],0,table(['Observed event','Meaning'],[['Module loaded','Its symbols/locations may become resolvable'],['Breakpoint resolved','An execution location is now available']]),['Module loading provides a location.','The application must still call that path to hit the breakpoint.','Resolved is not the same state as triggered.'],'Do not mark a breakpoint hit unless you observe the stop.');
 case 'conditional':return choice(`A breakpoint condition stops only when length == ${n}. This call has length ${n+1}. What happens?`,['It stops because a call occurred','It continues because the condition is false','It changes length to match'],1,table(['Condition','Observed value'],[[`length == ${n}`,n+1]]),[`Compare ${n+1} with ${n}.`,'The equality is false.','Under this stated conditional-breakpoint rule, execution continues.'],'A conditional stop requires both reaching the location and satisfying the condition.');
 case 'watchpoint':{const hit=2+h%2,events=[0,4,8].map((offset,i)=>[i+1,b+offset,1]);events[hit-1][1]=b+0x22;return num('Watching four bytes from BASE+0x20 through BASE+0x23 inclusive: which numbered write is the FIRST overlap?',hit,table(['Event / watched start','Write address','Bytes written'],[['Watched start',hex(b+0x20),4],...events.map(([i,a,n])=>[i,hex(a),n])]),[`The watched interval is ${hex(b+0x20)} through ${hex(b+0x23)}.`,`Compare each write range with that interval in event order.`,`Write ${hit} includes ${hex(b+0x22)} and is the first overlapping write.`],'This is a bounded access-overlap model. In a real debugger also inspect the surrounding instructions when the watchpoint fires.');}
 case 'stepping':{const into=Boolean(h%2);return choice(`At a CALL, you want to ${into?'inspect the called function’s first instructions':'continue to the instruction after the call without stepping through its body'}. Choose the command.`,['t','p','dd esp'],into?0:1,table(['Command','At a function call'],[['t','Step into'],['p','Step over']]),['First choose whether you need the callee’s internals.',into?'Use t to enter the called function.':'Use p to step over the call.','Neither command makes every possible application path execute.'],'The distinction matters at calls; use the smallest action that answers your current question.');}
 case 'rebase':return num('What is the corresponding runtime address?',b+0x340,table(['Quantity','Value'],[['Static base','0x00400000'],['Static item','0x00400340'],['Runtime base',hex(b)]]),['RVA = 0x00400340 − 0x00400000 = 0x340.',`Add 0x340 to the runtime base ${hex(b)}.`,`Runtime address = ${hex(b+0x340)}.`],'Use an offset from the same image build. A static virtual address is not automatically the live one.');
 case 'arithmetic':return num('How many BYTES apart are these two addresses?',n*16,table(['Address A','Address B'],[[hex(b),hex(b+n*16)]]),['Addresses count bytes in this model.',`Subtract ${hex(b)} from ${hex(b+n*16)}.`,`Difference = ${n*16} bytes (${hex(n*16)}).`],'Hexadecimal and decimal are representations of the same distance.');
 case 'bounds':return num('A counted copy writes the requested number of bytes. How many bytes extend beyond the destination capacity?',n,table(['Quantity','Bytes'],[['Destination capacity',16+n],['Requested copy',16+2*n]]),[`The destination has ${16+n} byte slots.`,`The request writes ${16+2*n} bytes.`,`Overflow amount = ${16+2*n} − ${16+n} = ${n} bytes.`],'This is explicitly a counted copy, not a null-terminated string copy. It does not assume what adjacent object gets overwritten.');
 case 'offset':return num('How many filler bytes come before this four-byte control slot?',n*8,table(['Input-relative field','Byte offset'],[['Input begins',0],['Control slot begins',n*8],['Control slot length',4]]),['An offset measures from the beginning of the input.',`The control slot starts at offset ${n*8}.`,`Use ${n*8} preceding bytes. The four-byte slot is counted separately.`],'Adding the slot length to the preceding filler would shift your controlled bytes past the intended field.');
 case 'badbytes':{const at=h%5,a=[0x21,0x32,0x43,0x54,0x65],z=[...a];z[at]=0;return num('At what ZERO-BASED byte offset is the first mismatch?',at,table(['Offset','Sent byte','Observed byte'],a.map((v,i)=>[i,v.toString(16),z[i].toString(16).padStart(2,'0')])),['Compare the bytes in increasing offset order.',`The first difference is at offset ${at}.`,'Investigate that change before interpreting later mismatches.'],'This evidence belongs to the tested input path. Do not assume a universal forbidden-byte list.');}
 case 'redirect':return choice('A candidate address worked once but points to unmapped memory after restart. Which assumption failed?', ['A fixed address would stay valid across these runs','Four bytes form a DWORD','The input contains any bytes at all'],0,table(['First run','Second run'],[['Candidate is mapped','Same candidate is unmapped']]),['The bytes may be unchanged while the destination moves.','A previously valid address is not evidence of current mapping.','Re-establish the address relationship and its other constraints.'],'One successful run is not proof of restart reliability.');
 case 'workspace':{const overlap=h%2===0;return choice('Do the written workspace bytes overlap bytes needed later? Ranges are inclusive.', ['Yes','No'],overlap?0:1,table(['Range','Start','End'],[['Needed later',hex(b),hex(b+31)],['Workspace writes',hex(overlap?b+24:b+32),hex(overlap?b+47:b+63)]]),['Write down the lower and upper bound of both ranges.',overlap?'Addresses from offset 24 through 31 are in both ranges.':'The workspace begins immediately after the last needed byte.',overlap?'They overlap. A write can damage bytes needed later.':'They do not overlap in this stated model.'],'Check boundaries, not just whether the start addresses differ.');}
 case 'seh':return num('What is the HANDLER address in the SECOND record?',b+0x800,table(['Record address','Next','Handler'],[[hex(b),hex(b+0x20),hex(b+0x700)],[hex(b+0x20),'0xFFFFFFFF',hex(b+0x800)]]),[`Record one’s Next points to ${hex(b+0x20)}.`,`Go to that record and read its Handler field.`,`The handler is ${hex(b+0x800)}; 0xFFFFFFFF here is the next-link sentinel.`],'Next links records. Handler identifies a function. They are not interchangeable pointers.');
 case 'validation':{const chain=Boolean(h%2);return choice(chain?'The integrity of the registration chain is being checked. Which source mechanism is this?':'A handler address is compared with a module’s safe-handler table. Which source mechanism is this?', ['SafeSEH','SEHOP'],chain?1:0,table(['Mechanism','Focus'],[['SafeSEH','Acceptable handler under module metadata'],['SEHOP','Registration-chain integrity']]),['Identify the object being checked.',chain?'This question concerns the linked chain.':'This question concerns membership in handler metadata.',chain?'That corresponds to SEHOP.':'That corresponds to SafeSEH.'],'Separate the two conditions before diagnosing a failure.');}
 case 'ppr':case 'rop':return num('After POP EAX; POP EBX; RET, what is the final ESP?',b+12,table(['Initial ESP / slots','Contents'],[['Initial ESP',hex(b)],[hex(b),'Data for EAX'],[hex(b+4),'Data for EBX'],[hex(b+8),'Next EIP']]),[`First POP consumes four bytes: ESP=${hex(b+4)}.`,`Second POP consumes four bytes: ESP=${hex(b+8)}.`,`RET consumes its destination: ESP=${hex(b+12)}.`],'Even an unwanted POP consumes a stack slot. This model excludes POP ESP and immediate RET cleanup.');
 case 'jump':{const d=(h%15)-7;return num('What is the destination of this two-byte relative jump?',b+2+d,table(['Instruction address','Length','Signed displacement'],[[hex(b),2,d]]),[`The next instruction would be at ${hex(b+2)}.`,`Add signed displacement ${d}.`,`Destination = ${hex(b+2+d)}.`],'The explicit model measures displacement from the end of the instruction.');}
 case 'branch':{const yes=Boolean(h%2);return choice(`Model: accept only when length >= ${n} AND tag == 0x46. Length=${yes?n:n-1}, tag=0x46. Which path is taken?`,['accept','reject'],yes?0:1,table(['Condition','Result'],[[`length >= ${n}`,String(yes)],['tag == 0x46','true']]),['Both sides of AND must be true.',yes?'The length reaches the threshold and the tag matches.':'The length is below the threshold; the tag cannot rescue it.',yes?'Take accept.':'Take reject.'],'Static paths show possibilities; this input’s conditions determine the observed path.');}
 case 'tag':{const at=8+h%5;return num('The complete eight-byte tag starts at the shown offset. Where does the payload begin?',b+at+8,table(['Location','Contents'],[[hex(b),'First half-tag only'],[hex(b+at),'TAG!TAG! (8 bytes)'],['Immediately afterward','Payload bytes']]),[`The full double tag begins at ${hex(b+at)}.`,'Move past all eight tag bytes.',`Payload begins at ${hex(b+at+8)}.`],'A half-tag is not a full match. Verify the buffer and its constraints separately.');}
 case 'page':{const a=b+0x73;return num('The page containing this address is unreadable. What is the NEXT page’s start?',Math.floor(a/4096)*4096+4096,table(['Address','Page size'],[[hex(a),'0x1000 bytes']]),[`Round ${hex(a)} down to ${hex(Math.floor(a/4096)*4096)} to identify its page start.`,'Add one whole page, 0x1000 bytes.',`Next page begins at ${hex(Math.floor(a/4096)*4096+4096)}.`],'The next byte can still belong to the same unreadable page.');}
 case 'portability':return choice('The debugger sees your buffer, but a probe calls every tested address unreadable after an OS-version change. What is the most useful next check?', ['Keep waiting without inspecting the probe','Compare the probe’s setup and returned result with this environment','Delete the known buffer'],1,table(['Confirmed','Unexpected'],[['Buffer is readable in debugger','Probe rejects known-readable locations']]),['Use the contradiction: the buffer exists, yet the probe classifies it incorrectly.','Inspect the probe inputs and result around the call.','Check the environmental assumptions before searching farther.'],'This narrows the failure. It does not establish a particular fix without the observations.');
 case 'calling':return num(`There are ${n} four-byte arguments under the stated __stdcall model. How many ARGUMENT bytes does the callee clean?`,n*4,table(['Parameter','Assumption'],[['Argument count',n],['Size per argument','4 bytes'],['Convention','__stdcall (x86)']]),[`Count ${n} arguments.`,`Multiply by four: ${n} × 4.`,`Argument cleanup = ${n*4} bytes. The return-address slot is separate.`],'Do not add return-address consumption when asked specifically for argument cleanup.');
 case 'list':return num('Follow BOTH pointer fields. What is the final stored value?',n*17,table(['Address','Stored DWORD'],[[hex(b+4),hex(b+0x80)],[hex(b+0x80+8),n*17]]),[`Start at base ${hex(b)}. The first field is at base+4.`,`Read its pointer (${hex(b+0x80)}), then add the second field offset 8.`,`Read ${hex(b+0x88)}: the value is ${n*17}.`],'The model’s field offsets are 4 and 8. Every arrow includes a field-location calculation and a read.');
 case 'exports':{const rva=0x210+n*16;return num('Resolve the name TutorMark using the three supplied arrays. What is its runtime address?',b+rva,table(['Array / quantity','Contents'],[['Names','[Alpha, TutorMark, Zeta]'],['Name ordinals','[2, 0, 1]'],['Function RVAs',`[${hex(rva)}, 0x510, 0x710]`],['Module base',hex(b)]]),['TutorMark has name index 1.','NameOrdinals[1] is 0, so read FunctionRVAs[0].',`That RVA is ${hex(rva)}. Add base ${hex(b)} to get ${hex(b+rva)}.`],'Name index 1 is not the function-array index. The ordinal table supplies that second index.');}
 case 'rotate':{const value=(0x100+n*2+1)>>>0,a=((value>>>1)|(value<<31))>>>0;return num('Rotate this 32-bit value RIGHT by ONE bit. What is the result?',a,table(['Value','Operation'],[[hex(value),'ROR by 1 bit']]),[`The low bit of ${hex(value)} is 1.`,'Move that bit to bit 31, and shift the remaining bits one place right.',`Result = ${hex(a)}.`],'A rotation wraps the outgoing bit around. A logical shift would discard it.');}
 case 'negate':{const target=n*16+3;return num(`Which 32-bit value becomes ${hex(target)} after NEG?`,(-target)>>>0,table(['Operation','Desired result'],[['NEG EAX (modulo 2^32)',hex(target)]]),[`Solve 0 − x ≡ ${target} modulo 2^32.`,`x = 2^32 − ${target}.`,`The 32-bit representation is ${hex((-target)>>>0)}.`],'This checks arithmetic only. You must separately inspect encoded instruction bytes and other side effects.');}
 case 'pic':return num('The runtime anchor is known. What is the address of the item 0x24 bytes after it?',b+0x24,table(['Quantity','Value'],[['Observed anchor',hex(b)],['Relative offset','0x24']]),['Use the current observed anchor, not yesterday’s absolute address.',`Add 0x24 to ${hex(b)}.`,`Result = ${hex(b+0x24)}.`],'The local offset stays valid only while the relevant code layout is unchanged.');
 case 'api':return choice('In copy(destination, source, byteCount), which value is the byteCount?', [hex(b),hex(b+0x100),String(n*4)],2,table(['Role','Value'],[['Destination address',hex(b)],['Source address',hex(b+0x100)],['Bytes to copy',n*4]]),['A destination is where the bytes go.','A source is where the bytes come from.',`The count is ${n*4} bytes, not either address.`],'Numbers have roles. Always label a call’s arguments before setting them.');
 case 'protocol':return num('This original record has a FOUR-byte length header. How many body bytes should its header declare?',n*12,table(['Quantity','Bytes'],[['Total record',4+n*12],['Header',4]]),['The stated header describes body length only.',`Subtract header size from total: ${4+n*12} − 4.`,`Body length = ${n*12} bytes.`],'This invented protocol is not the course application’s full protocol. Validate the length guard before investigating later operations.');
 case 'permissions':{const write=Boolean(h%2);return choice(`A page is readable and executable, but NOT writable. Is a ${write?'write to its data':'read of its bytes'} allowed by this model?`,['Yes','No'],write?1:0,table(['Read','Write','Execute'],[['Allowed','Not allowed','Allowed']]),[`Identify the requested operation: ${write?'write':'read'}.`,'Look at that permission, not the other columns.',write?'Write is disallowed.':'Read is allowed.'],'Page permissions are distinct. Seeing bytes in a debugger does not by itself establish execute or write permission.');}
 case 'callframe':return num(`At function entry, where is argument ${k}?`,b+4*k,table(['Location','Contents'],[['ESP',hex(b)],['[ESP]','Saved return address'],['[ESP+4]','Argument 1'],['[ESP+8]','Argument 2'],['[ESP+12]','Argument 3']]),['This snapshot is at entry, before a prologue changes ESP.',`Argument ${k} is ${k} four-byte slots after the return-address slot location.`,`Address = ${hex(b)} + ${k*4} = ${hex(b+4*k)}.`],'Timing matters. Do not reuse this layout after an unknown prologue without inspecting it.');
 case 'leak':return num('What is the runtime MODULE BASE?',b,table(['Quantity','Value'],[['Leaked address',hex(b+0x1350)],['RVA of leaked item','0x1350']]),['Confirm that the leak belongs to this exact module build.',`Subtract the known RVA 0x1350 from ${hex(b+0x1350)}.`,`Module base = ${hex(b)}.`],'Adding the RVA to the leak moves farther into the module; it does not locate the base.');
 case 'decode':{const carried=0xe0+h%16,target=h%16,a=(target-carried+256)%256;return num('What byte value must be ADDED modulo 256 to restore the desired byte?',a,table(['Transported byte','Desired byte'],[[hex(carried),hex(target)]]),[`Solve (${carried} + adjustment) mod 256 = ${target}.`,`Adjustment = (${target} − ${carried} + 256) mod 256.`,`Adjustment = ${a} (${hex(a)}).`],'Restore in the appropriate writable buffer before copying into a destination that the decoder cannot write.');}
 case 'format':return choice('Which statement lets user input control the FORMAT argument?', ['printf("%s", user_text)','printf(user_text)'],1,table(['Form','Format argument'],[['printf("%s", user_text)','Fixed literal'],['printf(user_text)','User-controlled text']]),['Identify the first argument, which supplies formatting instructions.','In the first form, user_text is data for a fixed %s format.','In the second, user_text itself supplies the format.'],'This identifies the dangerous role; the model does not execute the call or establish the exact exploitability of a particular runtime.');
 case 'readpath':return choice('The program reads a memory value into an internal log, but your script receives none of it. Which missing capability matters?', ['A way to retrieve the relevant output','More unrelated crash attempts','A different colour for the debugger'],0,table(['Completed link','Missing link'],[['Memory → internal log','Internal log → observable output']]),['A read inside the target is not yet a visible disclosure.','Trace how output can be retrieved through the available interface.','Check the returned bytes and their origin.'],'A useful read primitive needs an observable result, not only an internal operation.');
 case 'formatwrite':return num('In this ABSTRACT count model, how many additional characters reach the target count?',n*9,table(['Already counted','Target count'],[[n*5,n*14]]),[`The current count is ${n*5}.`,`The target is ${n*14}.`,`Additional count = ${n*14} − ${n*5} = ${n*9}.`],'This is arithmetic, not a claim that a particular printf implementation accepts a given write format.');
 case 'pivot':return num('ESP is moved to the chain start, then a plain RET executes. What is the final ESP?',b+0x104,table(['Quantity','Value'],[['New chain start',hex(b+0x100)],['First DWORD at new chain','Next instruction address']]),[`After the pivot, ESP=${hex(b+0x100)}.`,'RET consumes the four-byte destination at that new location.',`ESP becomes ${hex(b+0x104)}. EIP receives the consumed value.`],'The pivot changes the stack cursor; RET then uses that cursor. Track them as separate steps.');
 case 'workflow':{const replay=Boolean(h%2);return choice(replay?'An exercise worked once. What gives stronger evidence of reproducibility?':'A copied answer passes the worksheet. What gives stronger evidence of understanding?',replay?['Repeat from a clean state using the recorded steps','Add a completion badge','Delete the notes']:['Explain and solve a changed case without the answer','Copy it a second time','Mark the entire chapter mastered'],0,table(['Current evidence','Still missing'],[[replay?'One successful run':'One assisted answer',replay?'Clean reproduction':'Independent transfer']]),['Name what was actually observed.',replay?'One run leaves hidden state and omitted steps untested.':'Following an answer leaves your own reasoning untested.',replay?'Rebuild from a clean state and check the written procedure.':'Try a changed problem and explain the decisive step.'],'A checked model, real Windows observation and independent exploit are different levels of evidence.');}
 default:throw new Error(`No teaching model implemented for ${kind}`);
 }
}
export function check(x,input){
 if(typeof input!=='string'||input.length>160)return false;
 const s=input.trim();
 if(x.answerType==='number')return /^(0x[0-9a-f]+|[0-9]+)$/i.test(s)&&Number(s)===x.answer;
 if(x.answerType==='choice')return /^\d$/.test(s)&&Number(s)===x.answer;
 if(x.answerType==='bytes')return /^[0-9a-f]{2}(\s+[0-9a-f]{2}){3}$/i.test(s)&&s.toLowerCase().split(/\s+/).join(' ')===x.answer.toLowerCase();
 return s.toLowerCase()===String(x.answer).toLowerCase();
}
export function answerText(x){return x.answerType==='choice'?x.options[x.answer]:x.answerType==='number'?`${hex(x.answer)} (${x.answer} decimal)`:String(x.answer);}

const alternateChoices={
 debugger:['You want to inspect EAX while keeping execution paused. Which command fits?', ['g','r @eax','p'],1,['Name the desired observation: the value in EAX.','r @eax displays the register without stepping or resuming.','g continues execution; p steps an instruction.']],
 symbols:['A PDB exists but belongs to another build. What should you do?', ['Use its offsets as unquestionable truth','Find the PDB matching this executable','Conclude that all code is unreadable'],1,['Symbol information must match the executable build.','A similarly named PDB is not sufficient evidence.','Get matching symbols or keep your observations address-based.']],
 breakpoint:['A configured breakpoint never hits after you resume. What should you investigate?', ['Whether your input actually reaches that location','Whether bl executes more code','Whether a breakpoint is proof of execution'],0,['Configuration is not reachability evidence.','Trace the inputs and branches before the selected location.','Check that the module and address refer to the intended code.']],
 deferred:['A DLL is not loaded yet and you want a breakpoint when its function becomes available. Which command is intended for that?', ['bu module!function','dd module!function','r @eax'],0,['The function cannot yet be resolved to a loaded location.','bu keeps the unresolved function breakpoint until it can resolve.','Resolution still does not prove the function has executed.']],
 redirect:['An address exists, but the input parser truncates its encoded bytes. Which condition fails?', ['Transporting the destination intact','The definition of a pointer','Every process-memory mapping'],0,['The candidate must survive the input path as well as be mapped.','A truncated encoded address is not the destination you intended.','Test the actual bytes stored after input processing.']],
 portability:['A probe’s setup is unchanged, but the buffer bytes are missing in a new request layout. What do you verify first?', ['Whether the second buffer was stored completely in this path','A fixed syscall number without observing it','Only whether the app interface looks the same'],0,['This observation concerns buffer storage, not yet probe classification.','Trace how the new input layout is accepted and stored.','Confirm the full buffer before blaming the search mechanism.']],
 api:['A function expects a pointer to a four-byte result field. Which description matches that argument?', ['The address of writable result storage','The number four itself','The bytes of an unrelated function name'],0,['A pointer parameter receives a location.','Allocate or identify valid writable storage of the required size.','The storage size and its address remain different quantities.']],
 format:['A percent sequence occurs inside user_text passed to printf("%s", user_text). Which argument supplies the formatting instructions here?', ['The fixed "%s" literal','The percent sequence inside user_text','Both arguments become independent format strings'],0,['Identify the argument in the format position.','The fixed literal supplies the format instructions.','In this stated call, user_text is data for that format, not a second format argument.']],
 readpath:['Your script receives a hexadecimal-looking log line. What must you establish before treating it as a module-base leak?', ['What value it represents and where it originated','That every hexadecimal value is a module base','That its text length predicts exploit success'],0,['Representation alone does not identify the source of a value.','Trace its origin and determine whether it is a pointer, an offset or ordinary data.','Only then use a verified relationship to derive a module base.']]
};
export function exercise(kind,seed){
 let x=baseExercise(kind,seed);const h=hash(seed),a=alternateChoices[kind];
 if(kind==='stack'){
  const b=Number(x.display.rows[0][1]);
  x.states=[
   {registers:{ESP:hex(b-4),EAX:'0x00000007',EBX:'0x00000013',ECX:'unchanged'},memory:[[hex(b-4),'0x00000007','← ESP'],[hex(b),'older stack data','']]},
   {registers:{ESP:hex(b-8),EAX:'0x00000007',EBX:'0x00000013',ECX:'unchanged'},memory:[[hex(b-8),'0x00000013','← ESP'],[hex(b-4),'0x00000007',''],[hex(b),'older stack data','']]},
   {registers:{ESP:hex(b-4),EAX:'0x00000007',EBX:'0x00000013',ECX:'0x00000013'},memory:[[hex(b-8),'0x00000013','old bytes remain'],[hex(b-4),'0x00000007','← ESP'],[hex(b),'older stack data','']]}
  ];
 }
 if(kind==='pointer'){
  const b=Number(x.display.rows[0][1]),value=Number(x.display.rows[1][1]);
  x.states=[{registers:{EAX:hex(b),ECX:'not loaded yet'},memory:[[hex(b),hex(value),'pointed-to DWORD']]},{registers:{EAX:hex(b),ECX:'reading memory…'},memory:[[hex(b),hex(value),'read these contents']]},{registers:{EAX:hex(b),ECX:hex(value)},memory:[[hex(b),hex(value),'memory unchanged']]}];
 }

 if(a&&h%2)x={...x,prompt:a[0],options:a[1],answer:a[2],display:table(['Situation','Task'],[['Changed scenario','Follow the roles in the question']]),steps:a[3],hints:a[3].slice(0,2),explanation:a[3].join(' ')};
 if(x.answerType==='choice'){
  const order=x.options.map((_,i)=>i).sort((a,b)=>hash(seed+':option:'+a)-hash(seed+':option:'+b));
  x={...x,options:order.map(i=>x.options[i]),answer:order.indexOf(x.answer)};
 }
 return x;
}
